// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import { ComparisonOperator } from "./types";

export default {
  achievementId: __t.u32(),
  statTable: __t.string(),
  statField: __t.string(),
  get operator() {
    return ComparisonOperator;
  },
  thresholdValue: __t.u32(),
  filterGameMode: __t.option(__t.string()),
  filterCharacterName: __t.option(__t.string()),
  filterMatchType: __t.option(__t.string()),
};
