// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  RecurrenceRule,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  userId: __t.u32().name("user_id"),
  startAt: __t.timestamp().name("start_at"),
  endAt: __t.timestamp().name("end_at"),
  isRecurring: __t.bool().name("is_recurring"),
  get recurrenceRule() {
    return RecurrenceRule.name("recurrence_rule");
  },
  expiresAt: __t.timestamp().name("expires_at"),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
