// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  GameMode,
  BracketSide,
  MatchResultStatus,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  tournamentId: __t.u32().name("tournament_id"),
  roundNumber: __t.u32().name("round_number"),
  matchNumber: __t.u32().name("match_number"),
  get bracketSide() {
    return BracketSide.name("bracket_side");
  },
  groupId: __t.option(__t.u32()).name("group_id"),
  team1Id: __t.option(__t.u32()).name("team_1_id"),
  team2Id: __t.option(__t.u32()).name("team_2_id"),
  nextWinnerMatchId: __t.option(__t.u32()).name("next_winner_match_id"),
  nextLoserMatchId: __t.option(__t.u32()).name("next_loser_match_id"),
  bestOf: __t.u8().name("best_of"),
  get gameMode() {
    return GameMode.name("game_mode");
  },
  winnerAdvantage: __t.u8().name("winner_advantage"),
  scheduledAt: __t.option(__t.timestamp()).name("scheduled_at"),
  lobbyId: __t.option(__t.u32()).name("lobby_id"),
  checkInRequired: __t.bool().name("check_in_required"),
  winnerTeamId: __t.option(__t.u32()).name("winner_team_id"),
  get resultStatus() {
    return MatchResultStatus.name("result_status");
  },
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
