// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  GameMode,
  RosterVisibility,
  DisconnectPolicy,
  MatchType,
  DraftMode,
  BanMode,
} from "./types";

export default {
  name: __t.string(),
  teamSize: __t.u8(),
  get draftMode() {
    return DraftMode;
  },
  get banMode() {
    return BanMode;
  },
  get gameMode() {
    return GameMode;
  },
  get matchType() {
    return MatchType;
  },
  standardTurnSeconds: __t.u32(),
  reserveBankSeconds: __t.u32(),
  characterBudget: __t.f32(),
  lightconeBudget: __t.f32(),
  minimumBidRaise: __t.f32(),
  rosterDiffAdvantage: __t.f32(),
  rosterThreshold: __t.f32(),
  underThresholdAdvantage: __t.f32(),
  aboveThresholdPenalty: __t.f32(),
  deathPenalty: __t.f32(),
  isPublic: __t.bool(),
  isAnonymousPlayers: __t.bool(),
  isAnonymousSpectators: __t.bool(),
  get rosterVisibility() {
    return RosterVisibility;
  },
  requireOwnership: __t.bool(),
  costSetId: __t.u32(),
  get disconnectPolicy() {
    return DisconnectPolicy;
  },
  disconnectForfeitSeconds: __t.u32(),
  allowMirrorPicks: __t.bool(),
  autoRandomPick: __t.bool(),
  refereeCanUndo: __t.bool(),
  refereeCanPause: __t.bool(),
  refereeCanSetCaptain: __t.bool(),
  refereeCanKick: __t.bool(),
  allowPlayerPause: __t.bool(),
  refereeExclusiveConcede: __t.bool(),
};
