// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  kFactorNew: __t.u8().name("k_factor_new"),
  kFactorMid: __t.u8().name("k_factor_mid"),
  kFactorVet: __t.u8().name("k_factor_vet"),
  newThreshold: __t.u32().name("new_threshold"),
  midThreshold: __t.u32().name("mid_threshold"),
  initialRating: __t.u32().name("initial_rating"),
  sizeBonus: __t.u32().name("size_bonus"),
  spreadDivisor: __t.u8().name("spread_divisor"),
  maxAccountBonus: __t.u32().name("max_account_bonus"),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
