// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  GameMode,
  EidolonCost,
} from "./types";


export default __t.row({
  characterName: __t.string().name("character_name"),
  get gameMode() {
    return GameMode.name("game_mode");
  },
  get classicCosts() {
    return EidolonCost.name("classic_costs");
  },
  get auctionBaseBid() {
    return EidolonCost.name("auction_base_bid");
  },
});
