// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Path,
  Element,
  CharRole,
} from "./types";


export default __t.row({
  name: __t.string().primaryKey(),
  displayName: __t.string().name("display_name"),
  aliases: __t.array(__t.string()),
  rarity: __t.u8(),
  get path() {
    return Path;
  },
  get element() {
    return Element;
  },
  get role() {
    return CharRole;
  },
  imageUrl: __t.string().name("image_url"),
});
