// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  GameMode,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  sourceName: __t.string().name("source_name"),
  targetName: __t.string().name("target_name"),
  get gameMode() {
    return GameMode.name("game_mode");
  },
  costModifier: __t.f32().name("cost_modifier"),
});
