// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  SuperimpositionCost,
} from "./types";


export default __t.row({
  lightconeName: __t.string().primaryKey().name("lightcone_name"),
  get classicCosts() {
    return SuperimpositionCost.name("classic_costs");
  },
  get auctionBaseBid() {
    return SuperimpositionCost.name("auction_base_bid");
  },
});
