// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import { Path } from "./types";

export default __t.row({
  name: __t.string().primaryKey(),
  displayName: __t.string().name("display_name"),
  aliases: __t.array(__t.string()),
  get path() {
    return Path;
  },
  rarity: __t.u8(),
  imageUrl: __t.string().name("image_url"),
  posX: __t.i32().name("pos_x"),
  posY: __t.i32().name("pos_y"),
  width: __t.i32(),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
