// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  userId: __t.u32().name("user_id"),
  uid: __t.string(),
  region: __t.string(),
  displayLabel: __t.string().name("display_label"),
  isActive: __t.bool().name("is_active"),
  isRosterPublic: __t.bool().name("is_roster_public"),
  isRatingPublic: __t.bool().name("is_rating_public"),
  isDuplicateUid: __t.bool().name("is_duplicate_uid"),
  accountRating: __t.u32().name("account_rating"),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
