// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptTeamRequestReducer from "./accept_team_request_reducer";
import AddAchievementCriteriaReducer from "./add_achievement_criteria_reducer";
import AdminAssignCharacterArchetypesReducer from "./admin_assign_character_archetypes_reducer";
import AdminBatchRemoveCharactersReducer from "./admin_batch_remove_characters_reducer";
import AdminBatchUpsertCharactersReducer from "./admin_batch_upsert_characters_reducer";
import AdminBulkUpsertReducer from "./admin_bulk_upsert_reducer";
import AdminCreateHsrAccountReducer from "./admin_create_hsr_account_reducer";
import AdminDeleteArchetypeReducer from "./admin_delete_archetype_reducer";
import AdminDeleteHsrAccountReducer from "./admin_delete_hsr_account_reducer";
import AdminDeleteRowReducer from "./admin_delete_row_reducer";
import AdminRemoveCharacterArchetypesReducer from "./admin_remove_character_archetypes_reducer";
import AdminSeedEloConfigReducer from "./admin_seed_elo_config_reducer";
import AdminUpdateEloConfigReducer from "./admin_update_elo_config_reducer";
import AdminUpdateHsrAccountReducer from "./admin_update_hsr_account_reducer";
import AdminUpdateUserReducer from "./admin_update_user_reducer";
import AdminUpsertArchetypeReducer from "./admin_upsert_archetype_reducer";
import AdvanceBracketMatchReducer from "./advance_bracket_match_reducer";
import AdvanceStageReducer from "./advance_stage_reducer";
import AdvanceTournamentStageReducer from "./advance_tournament_stage_reducer";
import ApproveParticipantReducer from "./approve_participant_reducer";
import ApproveStandInReducer from "./approve_stand_in_reducer";
import ArrangeLineupReducer from "./arrange_lineup_reducer";
import AssignTournamentAssistantReducer from "./assign_tournament_assistant_reducer";
import BanCharacterReducer from "./ban_character_reducer";
import BanMemberReducer from "./ban_member_reducer";
import BatchRemoveCharactersReducer from "./batch_remove_characters_reducer";
import BatchUpsertCharactersReducer from "./batch_upsert_characters_reducer";
import BroadcastCursorReducer from "./broadcast_cursor_reducer";
import CancelTournamentReducer from "./cancel_tournament_reducer";
import CloseLobbyReducer from "./close_lobby_reducer";
import ConfirmLineupReducer from "./confirm_lineup_reducer";
import ConfirmMatchScoresReducer from "./confirm_match_scores_reducer";
import ConfirmReadyReducer from "./confirm_ready_reducer";
import CreateAchievementReducer from "./create_achievement_reducer";
import CreateAvailabilitySlotReducer from "./create_availability_slot_reducer";
import CreateCalendarEventReducer from "./create_calendar_event_reducer";
import CreateCostSetReducer from "./create_cost_set_reducer";
import CreateHsrAccountReducer from "./create_hsr_account_reducer";
import CreateLobbyReducer from "./create_lobby_reducer";
import CreateLobbyPresetReducer from "./create_lobby_preset_reducer";
import CreateSeasonReducer from "./create_season_reducer";
import CreateTournamentReducer from "./create_tournament_reducer";
import CreateTournamentLobbyReducer from "./create_tournament_lobby_reducer";
import CreateTournamentTeamReducer from "./create_tournament_team_reducer";
import DeleteAchievementReducer from "./delete_achievement_reducer";
import DeleteAvailabilitySlotReducer from "./delete_availability_slot_reducer";
import DeleteCalendarEventReducer from "./delete_calendar_event_reducer";
import DeleteChatMessageReducer from "./delete_chat_message_reducer";
import DeleteCostSetReducer from "./delete_cost_set_reducer";
import DeleteGuestAccountReducer from "./delete_guest_account_reducer";
import DeleteHsrAccountReducer from "./delete_hsr_account_reducer";
import DeleteLobbyPresetReducer from "./delete_lobby_preset_reducer";
import DisbandTournamentTeamReducer from "./disband_tournament_team_reducer";
import DisputeMatchResultReducer from "./dispute_match_result_reducer";
import DqParticipantReducer from "./dq_participant_reducer";
import EditDraftCharacterCostReducer from "./edit_draft_character_cost_reducer";
import EditDraftLightconeCostReducer from "./edit_draft_lightcone_cost_reducer";
import EditDraftSynergyCostReducer from "./edit_draft_synergy_cost_reducer";
import EquipLightconeReducer from "./equip_lightcone_reducer";
import FinalizeMatchResultReducer from "./finalize_match_result_reducer";
import GenerateBracketReducer from "./generate_bracket_reducer";
import InviteToEventReducer from "./invite_to_event_reducer";
import JoinLobbyReducer from "./join_lobby_reducer";
import KickMemberReducer from "./kick_member_reducer";
import LeaveLobbyReducer from "./leave_lobby_reducer";
import LeaveTournamentTeamReducer from "./leave_tournament_team_reducer";
import LockCostSetReducer from "./lock_cost_set_reducer";
import LoginAsGuestReducer from "./login_as_guest_reducer";
import ManualAwardAchievementReducer from "./manual_award_achievement_reducer";
import MigrateRosterReducer from "./migrate_roster_reducer";
import ModDemoteFromHostReducer from "./mod_demote_from_host_reducer";
import ModPromoteToHostReducer from "./mod_promote_to_host_reducer";
import NominateCharacterReducer from "./nominate_character_reducer";
import OverrideMatchResultReducer from "./override_match_result_reducer";
import PassBidReducer from "./pass_bid_reducer";
import PauseDraftReducer from "./pause_draft_reducer";
import PickCharacterReducer from "./pick_character_reducer";
import PlaceBidReducer from "./place_bid_reducer";
import ProcessTournamentMmrReducer from "./process_tournament_mmr_reducer";
import PublishCostSetReducer from "./publish_cost_set_reducer";
import ReclaimRefereeReducer from "./reclaim_referee_reducer";
import RecordGameScoresReducer from "./record_game_scores_reducer";
import RegisterForTournamentReducer from "./register_for_tournament_reducer";
import RegisterServerReducer from "./register_server_reducer";
import RejectTeamRequestReducer from "./reject_team_request_reducer";
import RemoveAchievementCriteriaReducer from "./remove_achievement_criteria_reducer";
import RemoveInviteReducer from "./remove_invite_reducer";
import RemoveTournamentAssistantReducer from "./remove_tournament_assistant_reducer";
import RequestJoinTeamReducer from "./request_join_team_reducer";
import RespondToInviteReducer from "./respond_to_invite_reducer";
import ResumeDraftReducer from "./resume_draft_reducer";
import RollbackBracketMatchReducer from "./rollback_bracket_match_reducer";
import SaveCalendarReducer from "./save_calendar_reducer";
import SeedBracketReducer from "./seed_bracket_reducer";
import SendChatMessageReducer from "./send_chat_message_reducer";
import ServerDeleteUserReducer from "./server_delete_user_reducer";
import ServerLinkDiscordReducer from "./server_link_discord_reducer";
import ServerSetMmrReducer from "./server_set_mmr_reducer";
import ServerSetRoleReducer from "./server_set_role_reducer";
import SetActiveHsrAccountReducer from "./set_active_hsr_account_reducer";
import SetActiveSeasonReducer from "./set_active_season_reducer";
import SetCaptainReducer from "./set_captain_reducer";
import SetDisplayedAchievementReducer from "./set_displayed_achievement_reducer";
import SetTeamSlotReducer from "./set_team_slot_reducer";
import StartDraftReducer from "./start_draft_reducer";
import SubmitAndAdvanceBracketReducer from "./submit_and_advance_bracket_reducer";
import SubmitMatchResultReducer from "./submit_match_result_reducer";
import SwapSeedsReducer from "./swap_seeds_reducer";
import TimerExpiryAuctionReducer from "./timer_expiry_auction_reducer";
import TimerExpiryClassicReducer from "./timer_expiry_classic_reducer";
import ToggleCalendarVisibilityReducer from "./toggle_calendar_visibility_reducer";
import TransferRefereeReducer from "./transfer_referee_reducer";
import UnconfirmReadyReducer from "./unconfirm_ready_reducer";
import UndoLastStepReducer from "./undo_last_step_reducer";
import UnpublishCostSetReducer from "./unpublish_cost_set_reducer";
import UnsaveCalendarReducer from "./unsave_calendar_reducer";
import UpdateAchievementReducer from "./update_achievement_reducer";
import UpdateAvailabilitySlotReducer from "./update_availability_slot_reducer";
import UpdateAvatarReducer from "./update_avatar_reducer";
import UpdateCalendarEventReducer from "./update_calendar_event_reducer";
import UpdateDisplayNameReducer from "./update_display_name_reducer";
import UpdateHsrAccountReducer from "./update_hsr_account_reducer";
import UpdateLobbyPresetReducer from "./update_lobby_preset_reducer";
import UpdateLobbySettingsReducer from "./update_lobby_settings_reducer";
import UpdateTournamentReducer from "./update_tournament_reducer";
import UpdateUsernameReducer from "./update_username_reducer";
import WaitlistPromoteReducer from "./waitlist_promote_reducer";
import WithdrawFromTournamentReducer from "./withdraw_from_tournament_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AchievementRow from "./achievement_table";
import AchievementCriteriaRow from "./achievement_criteria_table";
import ArchetypeRow from "./archetype_table";
import AvailabilitySlotRow from "./availability_slot_table";
import BracketMatchRow from "./bracket_match_table";
import CalendarEventRow from "./calendar_event_table";
import CalendarEventInviteRow from "./calendar_event_invite_table";
import ChatMessageRow from "./chat_message_table";
import CostSetRow from "./cost_set_table";
import EloConfigTableRow from "./elo_config_table_table";
import GlobalCharacterStatRow from "./global_character_stat_table";
import GroupStandingRow from "./group_standing_table";
import HsrAccountRow from "./hsr_account_table";
import HsrAccountCharacterRow from "./hsr_account_character_table";
import HsrAccountLightconeRow from "./hsr_account_lightcone_table";
import HsrCharacterRow from "./hsr_character_table";
import HsrCharacterArchetypeRow from "./hsr_character_archetype_table";
import HsrCharacterCostRow from "./hsr_character_cost_table";
import HsrLightconeRow from "./hsr_lightcone_table";
import HsrLightconeCostRow from "./hsr_lightcone_cost_table";
import HsrSynergyCostRow from "./hsr_synergy_cost_table";
import LeaderboardRow from "./leaderboard_table";
import LobbyRow from "./lobby_table";
import LobbyBanRow from "./lobby_ban_table";
import LobbyCursorEventRow from "./lobby_cursor_event_table";
import LobbyMemberRow from "./lobby_member_table";
import LobbyPresetRow from "./lobby_preset_table";
import MatchParticipantHistoryRow from "./match_participant_history_table";
import MatchResultGameRow from "./match_result_game_table";
import MatchResultGameHistoryRow from "./match_result_game_history_table";
import MatchResultParticipantRow from "./match_result_participant_table";
import MatchResultRecordRow from "./match_result_record_table";
import MatchSessionRow from "./match_session_table";
import MatchSessionHistoryRow from "./match_session_history_table";
import MatchSessionStepRow from "./match_session_step_table";
import MatchSessionStepHistoryRow from "./match_session_step_history_table";
import MmrHistoryRow from "./mmr_history_table";
import MmrRatingRow from "./mmr_rating_table";
import SavedCalendarRow from "./saved_calendar_table";
import SeasonRow from "./season_table";
import TournamentRow from "./tournament_table";
import TournamentAssistantRow from "./tournament_assistant_table";
import TournamentParticipantRow from "./tournament_participant_table";
import TournamentPlayerAccountRow from "./tournament_player_account_table";
import TournamentStandInRow from "./tournament_stand_in_table";
import TournamentTeamRow from "./tournament_team_table";
import TournamentTeamRequestRow from "./tournament_team_request_table";
import UserRow from "./user_table";
import UserAchievementRow from "./user_achievement_table";
import UserIdentityRow from "./user_identity_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  Achievement: __table({
    name: 'achievement',
    indexes: [
      { accessor: 'id', name: 'achievement_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'name', name: 'achievement_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
      { accessor: 'by_rarity', name: 'achievement_rarity_idx_btree', algorithm: 'btree', columns: [
        'rarity',
      ] },
    ],
    constraints: [
      { name: 'achievement_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'achievement_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, AchievementRow),
  AchievementCriteria: __table({
    name: 'achievement_criteria',
    indexes: [
      { accessor: 'by_achievement', name: 'achievement_criteria_achievement_id_idx_btree', algorithm: 'btree', columns: [
        'achievementId',
      ] },
      { accessor: 'id', name: 'achievement_criteria_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_stat_table', name: 'achievement_criteria_stat_table_idx_btree', algorithm: 'btree', columns: [
        'statTable',
      ] },
    ],
    constraints: [
      { name: 'achievement_criteria_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AchievementCriteriaRow),
  Archetype: __table({
    name: 'archetype',
    indexes: [
      { accessor: 'id', name: 'archetype_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'name', name: 'archetype_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'archetype_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'archetype_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, ArchetypeRow),
  AvailabilitySlot: __table({
    name: 'availability_slot',
    indexes: [
      { accessor: 'id', name: 'availability_slot_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'start_at', name: 'availability_slot_start_at_idx_btree', algorithm: 'btree', columns: [
        'startAt',
      ] },
      { accessor: 'user_id', name: 'availability_slot_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'availability_slot_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AvailabilitySlotRow),
  BracketMatch: __table({
    name: 'bracket_match',
    indexes: [
      { accessor: 'id', name: 'bracket_match_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'lobby_id', name: 'bracket_match_lobby_id_idx_btree', algorithm: 'btree', columns: [
        'lobbyId',
      ] },
      { accessor: 'tournament_id', name: 'bracket_match_tournament_id_idx_btree', algorithm: 'btree', columns: [
        'tournamentId',
      ] },
    ],
    constraints: [
      { name: 'bracket_match_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BracketMatchRow),
  CalendarEvent: __table({
    name: 'calendar_event',
    indexes: [
      { accessor: 'bracket_match_id', name: 'calendar_event_bracket_match_id_idx_btree', algorithm: 'btree', columns: [
        'bracketMatchId',
      ] },
      { accessor: 'id', name: 'calendar_event_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'organizer_id', name: 'calendar_event_organizer_id_idx_btree', algorithm: 'btree', columns: [
        'organizerId',
      ] },
      { accessor: 'start_at', name: 'calendar_event_start_at_idx_btree', algorithm: 'btree', columns: [
        'startAt',
      ] },
    ],
    constraints: [
      { name: 'calendar_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CalendarEventRow),
  CalendarEventInvite: __table({
    name: 'calendar_event_invite',
    indexes: [
      { accessor: 'event_id', name: 'calendar_event_invite_event_id_idx_btree', algorithm: 'btree', columns: [
        'eventId',
      ] },
      { accessor: 'by_event_and_invitee', name: 'calendar_event_invite_event_id_invitee_user_id_idx_btree', algorithm: 'btree', columns: [
        'eventId',
        'inviteeUserId',
      ] },
      { accessor: 'invitee_user_id', name: 'calendar_event_invite_invitee_user_id_idx_btree', algorithm: 'btree', columns: [
        'inviteeUserId',
      ] },
    ],
    constraints: [
    ],
  }, CalendarEventInviteRow),
  ChatMessage: __table({
    name: 'chat_message',
    indexes: [
      { accessor: 'id', name: 'chat_message_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'lobby_id', name: 'chat_message_lobby_id_idx_btree', algorithm: 'btree', columns: [
        'lobbyId',
      ] },
    ],
    constraints: [
      { name: 'chat_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatMessageRow),
  CostSet: __table({
    name: 'cost_set',
    indexes: [
      { accessor: 'creator_id', name: 'cost_set_creator_id_idx_btree', algorithm: 'btree', columns: [
        'creatorId',
      ] },
      { accessor: 'id', name: 'cost_set_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'cost_set_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CostSetRow),
  EloConfigTable: __table({
    name: 'elo_config',
    indexes: [
      { accessor: 'id', name: 'elo_config_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'elo_config_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EloConfigTableRow),
  GlobalCharacterStat: __table({
    name: 'global_character_stat',
    indexes: [
      { accessor: 'by_char_mode', name: 'global_character_stat_character_name_game_mode_idx_btree', algorithm: 'btree', columns: [
        'characterName',
        'gameMode',
      ] },
      { accessor: 'by_season', name: 'global_character_stat_season_id_idx_btree', algorithm: 'btree', columns: [
        'seasonId',
      ] },
    ],
    constraints: [
    ],
  }, GlobalCharacterStatRow),
  GroupStanding: __table({
    name: 'group_standing',
    indexes: [
      { accessor: 'by_tournament_group_and_team', name: 'group_standing_tournament_id_group_id_team_id_idx_btree', algorithm: 'btree', columns: [
        'tournamentId',
        'groupId',
        'teamId',
      ] },
      { accessor: 'tournament_id', name: 'group_standing_tournament_id_idx_btree', algorithm: 'btree', columns: [
        'tournamentId',
      ] },
    ],
    constraints: [
    ],
  }, GroupStandingRow),
  HsrAccount: __table({
    name: 'hsr_account',
    indexes: [
      { accessor: 'id', name: 'hsr_account_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'uid', name: 'hsr_account_uid_idx_btree', algorithm: 'btree', columns: [
        'uid',
      ] },
      { accessor: 'user_id', name: 'hsr_account_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'hsr_account_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, HsrAccountRow),
  HsrAccountCharacter: __table({
    name: 'hsr_account_character',
    indexes: [
      { accessor: 'by_account_and_character', name: 'hsr_account_character_hsr_account_id_character_name_idx_btree', algorithm: 'btree', columns: [
        'hsrAccountId',
        'characterName',
      ] },
      { accessor: 'hsr_account_id', name: 'hsr_account_character_hsr_account_id_idx_btree', algorithm: 'btree', columns: [
        'hsrAccountId',
      ] },
    ],
    constraints: [
    ],
  }, HsrAccountCharacterRow),
  HsrAccountLightcone: __table({
    name: 'hsr_account_lightcone',
    indexes: [
      { accessor: 'hsr_account_id', name: 'hsr_account_lightcone_hsr_account_id_idx_btree', algorithm: 'btree', columns: [
        'hsrAccountId',
      ] },
      { accessor: 'by_account_and_lightcone', name: 'hsr_account_lightcone_hsr_account_id_lightcone_name_idx_btree', algorithm: 'btree', columns: [
        'hsrAccountId',
        'lightconeName',
      ] },
    ],
    constraints: [
    ],
  }, HsrAccountLightconeRow),
  HsrCharacter: __table({
    name: 'hsr_character',
    indexes: [
      { accessor: 'by_element', name: 'hsr_character_element_idx_btree', algorithm: 'btree', columns: [
        'element',
      ] },
      { accessor: 'name', name: 'hsr_character_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
      { accessor: 'by_path', name: 'hsr_character_path_idx_btree', algorithm: 'btree', columns: [
        'path',
      ] },
      { accessor: 'by_role', name: 'hsr_character_role_idx_btree', algorithm: 'btree', columns: [
        'role',
      ] },
    ],
    constraints: [
      { name: 'hsr_character_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, HsrCharacterRow),
  HsrCharacterArchetype: __table({
    name: 'hsr_character_archetype',
    indexes: [
      { accessor: 'archetype_id', name: 'hsr_character_archetype_archetype_id_idx_btree', algorithm: 'btree', columns: [
        'archetypeId',
      ] },
      { accessor: 'by_character_and_archetype', name: 'hsr_character_archetype_character_name_archetype_id_idx_btree', algorithm: 'btree', columns: [
        'characterName',
        'archetypeId',
      ] },
      { accessor: 'character_name', name: 'hsr_character_archetype_character_name_idx_btree', algorithm: 'btree', columns: [
        'characterName',
      ] },
    ],
    constraints: [
    ],
  }, HsrCharacterArchetypeRow),
  HsrCharacterCost: __table({
    name: 'hsr_character_cost',
    indexes: [
      { accessor: 'by_character_mode_and_set', name: 'hsr_character_cost_character_name_game_mode_cost_set_id_idx_btree', algorithm: 'btree', columns: [
        'characterName',
        'gameMode',
        'costSetId',
      ] },
      { accessor: 'cost_set_id', name: 'hsr_character_cost_cost_set_id_idx_btree', algorithm: 'btree', columns: [
        'costSetId',
      ] },
    ],
    constraints: [
    ],
  }, HsrCharacterCostRow),
  HsrLightcone: __table({
    name: 'hsr_lightcone',
    indexes: [
      { accessor: 'name', name: 'hsr_lightcone_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
      { accessor: 'by_path', name: 'hsr_lightcone_path_idx_btree', algorithm: 'btree', columns: [
        'path',
      ] },
    ],
    constraints: [
      { name: 'hsr_lightcone_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, HsrLightconeRow),
  HsrLightconeCost: __table({
    name: 'hsr_lightcone_cost',
    indexes: [
      { accessor: 'cost_set_id', name: 'hsr_lightcone_cost_cost_set_id_idx_btree', algorithm: 'btree', columns: [
        'costSetId',
      ] },
      { accessor: 'by_lightcone_mode_and_set', name: 'hsr_lightcone_cost_lightcone_name_game_mode_cost_set_id_idx_btree', algorithm: 'btree', columns: [
        'lightconeName',
        'gameMode',
        'costSetId',
      ] },
    ],
    constraints: [
    ],
  }, HsrLightconeCostRow),
  HsrSynergyCost: __table({
    name: 'hsr_synergy_cost',
    indexes: [
      { accessor: 'cost_set_id', name: 'hsr_synergy_cost_cost_set_id_idx_btree', algorithm: 'btree', columns: [
        'costSetId',
      ] },
      { accessor: 'id', name: 'hsr_synergy_cost_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'source_mode', name: 'hsr_synergy_cost_source_name_game_mode_idx_btree', algorithm: 'btree', columns: [
        'sourceName',
        'gameMode',
      ] },
      { accessor: 'target_name', name: 'hsr_synergy_cost_target_name_idx_btree', algorithm: 'btree', columns: [
        'targetName',
      ] },
    ],
    constraints: [
      { name: 'hsr_synergy_cost_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, HsrSynergyCostRow),
  Leaderboard: __table({
    name: 'leaderboard',
    indexes: [
      { accessor: 'by_category_rank_season', name: 'leaderboard_category_rank_season_id_idx_btree', algorithm: 'btree', columns: [
        'category',
        'rank',
        'seasonId',
      ] },
      { accessor: 'by_user', name: 'leaderboard_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
    ],
  }, LeaderboardRow),
  Lobby: __table({
    name: 'lobby',
    indexes: [
      { accessor: 'host_user_id', name: 'lobby_host_user_id_idx_btree', algorithm: 'btree', columns: [
        'hostUserId',
      ] },
      { accessor: 'id', name: 'lobby_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'joinCode', name: 'lobby_join_code_idx_btree', algorithm: 'btree', columns: [
        'joinCode',
      ] },
      { accessor: 'stage', name: 'lobby_stage_idx_btree', algorithm: 'btree', columns: [
        'stage',
      ] },
      { accessor: 'tournament_id', name: 'lobby_tournament_id_idx_btree', algorithm: 'btree', columns: [
        'tournamentId',
      ] },
    ],
    constraints: [
      { name: 'lobby_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'lobby_join_code_key', constraint: 'unique', columns: ['joinCode'] },
    ],
  }, LobbyRow),
  LobbyBan: __table({
    name: 'lobby_ban',
    indexes: [
      { accessor: 'by_lobby_and_user', name: 'lobby_ban_lobby_id_banned_user_id_idx_btree', algorithm: 'btree', columns: [
        'lobbyId',
        'bannedUserId',
      ] },
      { accessor: 'lobby_id', name: 'lobby_ban_lobby_id_idx_btree', algorithm: 'btree', columns: [
        'lobbyId',
      ] },
    ],
    constraints: [
    ],
  }, LobbyBanRow),
  LobbyCursorEvent: __table({
    name: 'lobby_cursor_event',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, LobbyCursorEventRow),
  LobbyMember: __table({
    name: 'lobby_member',
    indexes: [
      { accessor: 'lobby_id', name: 'lobby_member_lobby_id_idx_btree', algorithm: 'btree', columns: [
        'lobbyId',
      ] },
      { accessor: 'by_lobby_and_user', name: 'lobby_member_lobby_id_user_id_idx_btree', algorithm: 'btree', columns: [
        'lobbyId',
        'userId',
      ] },
      { accessor: 'user_id', name: 'lobby_member_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
    ],
  }, LobbyMemberRow),
  LobbyPreset: __table({
    name: 'lobby_preset',
    indexes: [
      { accessor: 'creator_user_id', name: 'lobby_preset_creator_user_id_idx_btree', algorithm: 'btree', columns: [
        'creatorUserId',
      ] },
      { accessor: 'id', name: 'lobby_preset_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'lobby_preset_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LobbyPresetRow),
  MatchParticipantHistory: __table({
    name: 'match_participant_history',
    indexes: [
      { accessor: 'by_match_history', name: 'match_participant_history_match_history_id_idx_btree', algorithm: 'btree', columns: [
        'matchHistoryId',
      ] },
      { accessor: 'by_user', name: 'match_participant_history_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
      { accessor: 'by_user_and_match', name: 'match_participant_history_user_id_match_history_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
        'matchHistoryId',
      ] },
    ],
    constraints: [
    ],
  }, MatchParticipantHistoryRow),
  MatchResultGame: __table({
    name: 'match_result_game',
    indexes: [
      { accessor: 'by_result_and_game', name: 'match_result_game_match_result_id_game_number_idx_btree', algorithm: 'btree', columns: [
        'matchResultId',
        'gameNumber',
      ] },
      { accessor: 'match_result_id', name: 'match_result_game_match_result_id_idx_btree', algorithm: 'btree', columns: [
        'matchResultId',
      ] },
    ],
    constraints: [
    ],
  }, MatchResultGameRow),
  MatchResultGameHistory: __table({
    name: 'match_result_game_history',
    indexes: [
      { accessor: 'by_match_history', name: 'match_result_game_history_match_history_id_idx_btree', algorithm: 'btree', columns: [
        'matchHistoryId',
      ] },
    ],
    constraints: [
    ],
  }, MatchResultGameHistoryRow),
  MatchResultParticipant: __table({
    name: 'match_result_participant',
    indexes: [
      { accessor: 'match_result_id', name: 'match_result_participant_match_result_id_idx_btree', algorithm: 'btree', columns: [
        'matchResultId',
      ] },
      { accessor: 'by_result_and_user', name: 'match_result_participant_match_result_id_user_id_idx_btree', algorithm: 'btree', columns: [
        'matchResultId',
        'userId',
      ] },
      { accessor: 'user_id', name: 'match_result_participant_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
    ],
  }, MatchResultParticipantRow),
  MatchResultRecord: __table({
    name: 'match_result_record',
    indexes: [
      { accessor: 'id', name: 'match_result_record_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'lobby_id', name: 'match_result_record_lobby_id_idx_btree', algorithm: 'btree', columns: [
        'lobbyId',
      ] },
      { accessor: 'tournament_id', name: 'match_result_record_tournament_id_idx_btree', algorithm: 'btree', columns: [
        'tournamentId',
      ] },
    ],
    constraints: [
      { name: 'match_result_record_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MatchResultRecordRow),
  MatchSession: __table({
    name: 'match_session',
    indexes: [
      { accessor: 'lobbyId', name: 'match_session_lobby_id_idx_btree', algorithm: 'btree', columns: [
        'lobbyId',
      ] },
    ],
    constraints: [
      { name: 'match_session_lobby_id_key', constraint: 'unique', columns: ['lobbyId'] },
    ],
  }, MatchSessionRow),
  MatchSessionHistory: __table({
    name: 'match_session_history',
    indexes: [
      { accessor: 'game_mode', name: 'match_session_history_game_mode_idx_btree', algorithm: 'btree', columns: [
        'gameMode',
      ] },
      { accessor: 'id', name: 'match_session_history_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'played_at', name: 'match_session_history_played_at_idx_btree', algorithm: 'btree', columns: [
        'playedAt',
      ] },
    ],
    constraints: [
      { name: 'match_session_history_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MatchSessionHistoryRow),
  MatchSessionStep: __table({
    name: 'match_session_step',
    indexes: [
      { accessor: 'id', name: 'match_session_step_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'lobby_id', name: 'match_session_step_lobby_id_idx_btree', algorithm: 'btree', columns: [
        'lobbyId',
      ] },
    ],
    constraints: [
      { name: 'match_session_step_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MatchSessionStepRow),
  MatchSessionStepHistory: __table({
    name: 'match_session_step_history',
    indexes: [
      { accessor: 'by_match_history', name: 'match_session_step_history_match_history_id_idx_btree', algorithm: 'btree', columns: [
        'matchHistoryId',
      ] },
    ],
    constraints: [
    ],
  }, MatchSessionStepHistoryRow),
  MmrHistory: __table({
    name: 'mmr_history',
    indexes: [
      { accessor: 'id', name: 'mmr_history_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'match_history_id', name: 'mmr_history_match_history_id_idx_btree', algorithm: 'btree', columns: [
        'matchHistoryId',
      ] },
      { accessor: 'user_id', name: 'mmr_history_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'mmr_history_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MmrHistoryRow),
  MmrRating: __table({
    name: 'mmr_rating',
    indexes: [
      { accessor: 'rating', name: 'mmr_rating_rating_idx_btree', algorithm: 'btree', columns: [
        'rating',
      ] },
      { accessor: 'by_user_mode_season', name: 'mmr_rating_user_id_game_mode_season_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
        'gameMode',
        'seasonId',
      ] },
      { accessor: 'user_id', name: 'mmr_rating_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
    ],
  }, MmrRatingRow),
  SavedCalendar: __table({
    name: 'saved_calendar',
    indexes: [
      { accessor: 'user_id', name: 'saved_calendar_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
      { accessor: 'by_user_and_target', name: 'saved_calendar_user_id_target_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
        'targetUserId',
      ] },
    ],
    constraints: [
    ],
  }, SavedCalendarRow),
  Season: __table({
    name: 'season',
    indexes: [
      { accessor: 'id', name: 'season_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'is_active', name: 'season_is_active_idx_btree', algorithm: 'btree', columns: [
        'isActive',
      ] },
    ],
    constraints: [
      { name: 'season_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SeasonRow),
  Tournament: __table({
    name: 'tournament',
    indexes: [
      { accessor: 'id', name: 'tournament_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'organizer_id', name: 'tournament_organizer_id_idx_btree', algorithm: 'btree', columns: [
        'organizerId',
      ] },
      { accessor: 'stage', name: 'tournament_stage_idx_btree', algorithm: 'btree', columns: [
        'stage',
      ] },
    ],
    constraints: [
      { name: 'tournament_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TournamentRow),
  TournamentAssistant: __table({
    name: 'tournament_assistant',
    indexes: [
      { accessor: 'tournament_id', name: 'tournament_assistant_tournament_id_idx_btree', algorithm: 'btree', columns: [
        'tournamentId',
      ] },
      { accessor: 'by_tournament_and_user', name: 'tournament_assistant_tournament_id_user_id_idx_btree', algorithm: 'btree', columns: [
        'tournamentId',
        'userId',
      ] },
      { accessor: 'user_id', name: 'tournament_assistant_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
    ],
  }, TournamentAssistantRow),
  TournamentParticipant: __table({
    name: 'tournament_participant',
    indexes: [
      { accessor: 'tournament_id', name: 'tournament_participant_tournament_id_idx_btree', algorithm: 'btree', columns: [
        'tournamentId',
      ] },
      { accessor: 'by_tournament_and_user', name: 'tournament_participant_tournament_id_user_id_idx_btree', algorithm: 'btree', columns: [
        'tournamentId',
        'userId',
      ] },
      { accessor: 'user_id', name: 'tournament_participant_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
    ],
  }, TournamentParticipantRow),
  TournamentPlayerAccount: __table({
    name: 'tournament_player_account',
    indexes: [
      { accessor: 'by_tournament_and_user', name: 'tournament_player_account_tournament_id_user_id_idx_btree', algorithm: 'btree', columns: [
        'tournamentId',
        'userId',
      ] },
      { accessor: 'by_user', name: 'tournament_player_account_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
    ],
  }, TournamentPlayerAccountRow),
  TournamentStandIn: __table({
    name: 'tournament_stand_in',
    indexes: [
      { accessor: 'bracket_match_id', name: 'tournament_stand_in_bracket_match_id_idx_btree', algorithm: 'btree', columns: [
        'bracketMatchId',
      ] },
      { accessor: 'by_match_and_user', name: 'tournament_stand_in_bracket_match_id_user_id_idx_btree', algorithm: 'btree', columns: [
        'bracketMatchId',
        'userId',
      ] },
    ],
    constraints: [
    ],
  }, TournamentStandInRow),
  TournamentTeam: __table({
    name: 'tournament_team',
    indexes: [
      { accessor: 'captain_user_id', name: 'tournament_team_captain_user_id_idx_btree', algorithm: 'btree', columns: [
        'captainUserId',
      ] },
      { accessor: 'id', name: 'tournament_team_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'tournament_id', name: 'tournament_team_tournament_id_idx_btree', algorithm: 'btree', columns: [
        'tournamentId',
      ] },
    ],
    constraints: [
      { name: 'tournament_team_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TournamentTeamRow),
  TournamentTeamRequest: __table({
    name: 'tournament_team_request',
    indexes: [
      { accessor: 'team_id', name: 'tournament_team_request_team_id_idx_btree', algorithm: 'btree', columns: [
        'teamId',
      ] },
      { accessor: 'by_team_and_user', name: 'tournament_team_request_team_id_user_id_idx_btree', algorithm: 'btree', columns: [
        'teamId',
        'userId',
      ] },
      { accessor: 'user_id', name: 'tournament_team_request_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
    ],
  }, TournamentTeamRequestRow),
  User: __table({
    name: 'user',
    indexes: [
      { accessor: 'discord_id', name: 'user_discord_id_idx_btree', algorithm: 'btree', columns: [
        'discordId',
      ] },
      { accessor: 'id', name: 'user_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'username', name: 'user_username_idx_btree', algorithm: 'btree', columns: [
        'username',
      ] },
    ],
    constraints: [
      { name: 'user_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'user_username_key', constraint: 'unique', columns: ['username'] },
    ],
  }, UserRow),
  UserAchievement: __table({
    name: 'user_achievement',
    indexes: [
      { accessor: 'by_achievement', name: 'user_achievement_achievement_id_idx_btree', algorithm: 'btree', columns: [
        'achievementId',
      ] },
      { accessor: 'id', name: 'user_achievement_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_user_achievement', name: 'user_achievement_user_id_achievement_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
        'achievementId',
      ] },
      { accessor: 'by_user', name: 'user_achievement_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'user_achievement_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserAchievementRow),
  UserIdentity: __table({
    name: 'user_identity',
    indexes: [
      { accessor: 'identity', name: 'user_identity_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'user_id', name: 'user_identity_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'user_identity_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserIdentityRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_team_request", AcceptTeamRequestReducer),
  __reducerSchema("add_achievement_criteria", AddAchievementCriteriaReducer),
  __reducerSchema("admin_assign_character_archetypes", AdminAssignCharacterArchetypesReducer),
  __reducerSchema("admin_batch_remove_characters", AdminBatchRemoveCharactersReducer),
  __reducerSchema("admin_batch_upsert_characters", AdminBatchUpsertCharactersReducer),
  __reducerSchema("admin_bulk_upsert", AdminBulkUpsertReducer),
  __reducerSchema("admin_create_hsr_account", AdminCreateHsrAccountReducer),
  __reducerSchema("admin_delete_archetype", AdminDeleteArchetypeReducer),
  __reducerSchema("admin_delete_hsr_account", AdminDeleteHsrAccountReducer),
  __reducerSchema("admin_delete_row", AdminDeleteRowReducer),
  __reducerSchema("admin_remove_character_archetypes", AdminRemoveCharacterArchetypesReducer),
  __reducerSchema("admin_seed_elo_config", AdminSeedEloConfigReducer),
  __reducerSchema("admin_update_elo_config", AdminUpdateEloConfigReducer),
  __reducerSchema("admin_update_hsr_account", AdminUpdateHsrAccountReducer),
  __reducerSchema("admin_update_user", AdminUpdateUserReducer),
  __reducerSchema("admin_upsert_archetype", AdminUpsertArchetypeReducer),
  __reducerSchema("advance_bracket_match", AdvanceBracketMatchReducer),
  __reducerSchema("advance_stage", AdvanceStageReducer),
  __reducerSchema("advance_tournament_stage", AdvanceTournamentStageReducer),
  __reducerSchema("approve_participant", ApproveParticipantReducer),
  __reducerSchema("approve_stand_in", ApproveStandInReducer),
  __reducerSchema("arrange_lineup", ArrangeLineupReducer),
  __reducerSchema("assign_tournament_assistant", AssignTournamentAssistantReducer),
  __reducerSchema("ban_character", BanCharacterReducer),
  __reducerSchema("ban_member", BanMemberReducer),
  __reducerSchema("batch_remove_characters", BatchRemoveCharactersReducer),
  __reducerSchema("batch_upsert_characters", BatchUpsertCharactersReducer),
  __reducerSchema("broadcast_cursor", BroadcastCursorReducer),
  __reducerSchema("cancel_tournament", CancelTournamentReducer),
  __reducerSchema("close_lobby", CloseLobbyReducer),
  __reducerSchema("confirm_lineup", ConfirmLineupReducer),
  __reducerSchema("confirm_match_scores", ConfirmMatchScoresReducer),
  __reducerSchema("confirm_ready", ConfirmReadyReducer),
  __reducerSchema("create_achievement", CreateAchievementReducer),
  __reducerSchema("create_availability_slot", CreateAvailabilitySlotReducer),
  __reducerSchema("create_calendar_event", CreateCalendarEventReducer),
  __reducerSchema("create_cost_set", CreateCostSetReducer),
  __reducerSchema("create_hsr_account", CreateHsrAccountReducer),
  __reducerSchema("create_lobby", CreateLobbyReducer),
  __reducerSchema("create_lobby_preset", CreateLobbyPresetReducer),
  __reducerSchema("create_season", CreateSeasonReducer),
  __reducerSchema("create_tournament", CreateTournamentReducer),
  __reducerSchema("create_tournament_lobby", CreateTournamentLobbyReducer),
  __reducerSchema("create_tournament_team", CreateTournamentTeamReducer),
  __reducerSchema("delete_achievement", DeleteAchievementReducer),
  __reducerSchema("delete_availability_slot", DeleteAvailabilitySlotReducer),
  __reducerSchema("delete_calendar_event", DeleteCalendarEventReducer),
  __reducerSchema("delete_chat_message", DeleteChatMessageReducer),
  __reducerSchema("delete_cost_set", DeleteCostSetReducer),
  __reducerSchema("delete_guest_account", DeleteGuestAccountReducer),
  __reducerSchema("delete_hsr_account", DeleteHsrAccountReducer),
  __reducerSchema("delete_lobby_preset", DeleteLobbyPresetReducer),
  __reducerSchema("disband_tournament_team", DisbandTournamentTeamReducer),
  __reducerSchema("dispute_match_result", DisputeMatchResultReducer),
  __reducerSchema("dq_participant", DqParticipantReducer),
  __reducerSchema("edit_draft_character_cost", EditDraftCharacterCostReducer),
  __reducerSchema("edit_draft_lightcone_cost", EditDraftLightconeCostReducer),
  __reducerSchema("edit_draft_synergy_cost", EditDraftSynergyCostReducer),
  __reducerSchema("equip_lightcone", EquipLightconeReducer),
  __reducerSchema("finalize_match_result", FinalizeMatchResultReducer),
  __reducerSchema("generate_bracket", GenerateBracketReducer),
  __reducerSchema("invite_to_event", InviteToEventReducer),
  __reducerSchema("join_lobby", JoinLobbyReducer),
  __reducerSchema("kick_member", KickMemberReducer),
  __reducerSchema("leave_lobby", LeaveLobbyReducer),
  __reducerSchema("leave_tournament_team", LeaveTournamentTeamReducer),
  __reducerSchema("lock_cost_set", LockCostSetReducer),
  __reducerSchema("login_as_guest", LoginAsGuestReducer),
  __reducerSchema("manual_award_achievement", ManualAwardAchievementReducer),
  __reducerSchema("migrate_roster", MigrateRosterReducer),
  __reducerSchema("mod_demote_from_host", ModDemoteFromHostReducer),
  __reducerSchema("mod_promote_to_host", ModPromoteToHostReducer),
  __reducerSchema("nominate_character", NominateCharacterReducer),
  __reducerSchema("override_match_result", OverrideMatchResultReducer),
  __reducerSchema("pass_bid", PassBidReducer),
  __reducerSchema("pause_draft", PauseDraftReducer),
  __reducerSchema("pick_character", PickCharacterReducer),
  __reducerSchema("place_bid", PlaceBidReducer),
  __reducerSchema("process_tournament_mmr", ProcessTournamentMmrReducer),
  __reducerSchema("publish_cost_set", PublishCostSetReducer),
  __reducerSchema("reclaim_referee", ReclaimRefereeReducer),
  __reducerSchema("record_game_scores", RecordGameScoresReducer),
  __reducerSchema("register_for_tournament", RegisterForTournamentReducer),
  __reducerSchema("register_server", RegisterServerReducer),
  __reducerSchema("reject_team_request", RejectTeamRequestReducer),
  __reducerSchema("remove_achievement_criteria", RemoveAchievementCriteriaReducer),
  __reducerSchema("remove_invite", RemoveInviteReducer),
  __reducerSchema("remove_tournament_assistant", RemoveTournamentAssistantReducer),
  __reducerSchema("request_join_team", RequestJoinTeamReducer),
  __reducerSchema("respond_to_invite", RespondToInviteReducer),
  __reducerSchema("resume_draft", ResumeDraftReducer),
  __reducerSchema("rollback_bracket_match", RollbackBracketMatchReducer),
  __reducerSchema("save_calendar", SaveCalendarReducer),
  __reducerSchema("seed_bracket", SeedBracketReducer),
  __reducerSchema("send_chat_message", SendChatMessageReducer),
  __reducerSchema("server_delete_user", ServerDeleteUserReducer),
  __reducerSchema("server_link_discord", ServerLinkDiscordReducer),
  __reducerSchema("server_set_mmr", ServerSetMmrReducer),
  __reducerSchema("server_set_role", ServerSetRoleReducer),
  __reducerSchema("set_active_hsr_account", SetActiveHsrAccountReducer),
  __reducerSchema("set_active_season", SetActiveSeasonReducer),
  __reducerSchema("set_captain", SetCaptainReducer),
  __reducerSchema("set_displayed_achievement", SetDisplayedAchievementReducer),
  __reducerSchema("set_team_slot", SetTeamSlotReducer),
  __reducerSchema("start_draft", StartDraftReducer),
  __reducerSchema("submit_and_advance_bracket", SubmitAndAdvanceBracketReducer),
  __reducerSchema("submit_match_result", SubmitMatchResultReducer),
  __reducerSchema("swap_seeds", SwapSeedsReducer),
  __reducerSchema("timer_expiry_auction", TimerExpiryAuctionReducer),
  __reducerSchema("timer_expiry_classic", TimerExpiryClassicReducer),
  __reducerSchema("toggle_calendar_visibility", ToggleCalendarVisibilityReducer),
  __reducerSchema("transfer_referee", TransferRefereeReducer),
  __reducerSchema("unconfirm_ready", UnconfirmReadyReducer),
  __reducerSchema("undo_last_step", UndoLastStepReducer),
  __reducerSchema("unpublish_cost_set", UnpublishCostSetReducer),
  __reducerSchema("unsave_calendar", UnsaveCalendarReducer),
  __reducerSchema("update_achievement", UpdateAchievementReducer),
  __reducerSchema("update_availability_slot", UpdateAvailabilitySlotReducer),
  __reducerSchema("update_avatar", UpdateAvatarReducer),
  __reducerSchema("update_calendar_event", UpdateCalendarEventReducer),
  __reducerSchema("update_display_name", UpdateDisplayNameReducer),
  __reducerSchema("update_hsr_account", UpdateHsrAccountReducer),
  __reducerSchema("update_lobby_preset", UpdateLobbyPresetReducer),
  __reducerSchema("update_lobby_settings", UpdateLobbySettingsReducer),
  __reducerSchema("update_tournament", UpdateTournamentReducer),
  __reducerSchema("update_username", UpdateUsernameReducer),
  __reducerSchema("waitlist_promote", WaitlistPromoteReducer),
  __reducerSchema("withdraw_from_tournament", WithdrawFromTournamentReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.1.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

