// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  TeamLabel,
  ParticipationRole,
} from "./types";


export default __t.row({
  lobbyId: __t.u32().name("lobby_id"),
  userId: __t.u32().name("user_id"),
  isOnline: __t.bool().name("is_online"),
  get participationRole() {
    return ParticipationRole.name("participation_role");
  },
  isReferee: __t.bool().name("is_referee"),
  isCoach: __t.bool().name("is_coach"),
  get teamSlot() {
    return TeamLabel.name("team_slot");
  },
  isConfirmed: __t.bool().name("is_confirmed"),
  isCaptain: __t.bool().name("is_captain"),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
