// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  LobbyStage,
  LobbyConfig,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  joinCode: __t.string().name("join_code"),
  hostIdentity: __t.identity().name("host_identity"),
  teamBlueAlias: __t.string().name("team_blue_alias"),
  teamRedAlias: __t.string().name("team_red_alias"),
  hostDisconnectTime: __t.option(__t.timestamp()).name("host_disconnect_time"),
  lastActivityAt: __t.timestamp().name("last_activity_at"),
  get stage() {
    return LobbyStage;
  },
  get config() {
    return LobbyConfig;
  },
});
