// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  GameMode,
  DisconnectPolicy,
  DraftMode,
  BanMode,
  LobbyStage,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  joinCode: __t.string().name("join_code"),
  hostUserId: __t.u32().name("host_user_id"),
  teamBlueAlias: __t.string().name("team_blue_alias"),
  teamRedAlias: __t.string().name("team_red_alias"),
  teamSize: __t.u8().name("team_size"),
  get draftMode() {
    return DraftMode.name("draft_mode");
  },
  get banMode() {
    return BanMode.name("ban_mode");
  },
  standardTurnSeconds: __t.u32().name("standard_turn_seconds"),
  reserveBankSeconds: __t.u32().name("reserve_bank_seconds"),
  auctionBudget: __t.option(__t.f32()).name("auction_budget"),
  rosterDiffAdvantage: __t.f32().name("roster_diff_advantage"),
  rosterThreshold: __t.f32().name("roster_threshold"),
  underThresholdAdvantage: __t.f32().name("under_threshold_advantage"),
  aboveThresholdPenalty: __t.f32().name("above_threshold_penalty"),
  deathPenalty: __t.f32().name("death_penalty"),
  tournamentId: __t.option(__t.u32()).name("tournament_id"),
  bracketMatchId: __t.option(__t.u32()).name("bracket_match_id"),
  isAnonymousPlayers: __t.bool().name("is_anonymous_players"),
  isAnonymousSpectators: __t.bool().name("is_anonymous_spectators"),
  isOpenRoster: __t.bool().name("is_open_roster"),
  costSetId: __t.u32().name("cost_set_id"),
  isPublic: __t.bool().name("is_public"),
  get disconnectPolicy() {
    return DisconnectPolicy.name("disconnect_policy");
  },
  get gameMode() {
    return GameMode.name("game_mode");
  },
  hostDisconnectTime: __t.option(__t.timestamp()).name("host_disconnect_time"),
  lastActivityAt: __t.timestamp().name("last_activity_at"),
  get stage() {
    return LobbyStage;
  },
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
