// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  GameMode,
  DraftMode,
  RosterVisibility,
  DisconnectPolicy,
  MatchType,
  BanMode,
} from "./types";

export default __t.row({
  id: __t.u32().primaryKey(),
  name: __t.string(),
  isSystemPreset: __t.bool().name("is_system_preset"),
  creatorUserId: __t.u32().name("creator_user_id"),
  teamSize: __t.u8().name("team_size"),
  get draftMode() {
    return DraftMode.name("draft_mode");
  },
  get banMode() {
    return BanMode.name("ban_mode");
  },
  get gameMode() {
    return GameMode.name("game_mode");
  },
  get matchType() {
    return MatchType.name("match_type");
  },
  standardTurnSeconds: __t.u32().name("standard_turn_seconds"),
  reserveBankSeconds: __t.u32().name("reserve_bank_seconds"),
  characterBudget: __t.f32().name("character_budget"),
  lightconeBudget: __t.f32().name("lightcone_budget"),
  minimumBidRaise: __t.f32().name("minimum_bid_raise"),
  rosterDiffAdvantage: __t.f32().name("roster_diff_advantage"),
  rosterThreshold: __t.f32().name("roster_threshold"),
  underThresholdAdvantage: __t.f32().name("under_threshold_advantage"),
  aboveThresholdPenalty: __t.f32().name("above_threshold_penalty"),
  deathPenalty: __t.f32().name("death_penalty"),
  isPublic: __t.bool().name("is_public"),
  isAnonymousPlayers: __t.bool().name("is_anonymous_players"),
  isAnonymousSpectators: __t.bool().name("is_anonymous_spectators"),
  get rosterVisibility() {
    return RosterVisibility.name("roster_visibility");
  },
  requireOwnership: __t.bool().name("require_ownership"),
  costSetId: __t.u32().name("cost_set_id"),
  get disconnectPolicy() {
    return DisconnectPolicy.name("disconnect_policy");
  },
  disconnectForfeitSeconds: __t
    .option(__t.u32())
    .name("disconnect_forfeit_seconds"),
  allowMirrorPicks: __t.bool().name("allow_mirror_picks"),
  autoRandomPick: __t.bool().name("auto_random_pick"),
  refereeCanUndo: __t.bool().name("referee_can_undo"),
  refereeCanPause: __t.bool().name("referee_can_pause"),
  refereeCanSetCaptain: __t.bool().name("referee_can_set_captain"),
  refereeCanKick: __t.bool().name("referee_can_kick"),
  allowPlayerPause: __t.bool().name("allow_player_pause"),
  refereeExclusiveConcede: __t.bool().name("referee_exclusive_concede"),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
