// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  TeamLabel,
  ActionType,
  StepPayload,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  lobbyId: __t.u32().name("lobby_id"),
  sequence: __t.u32(),
  actorUserId: __t.u32().name("actor_user_id"),
  get actorSlot() {
    return TeamLabel.name("actor_slot");
  },
  get action() {
    return ActionType;
  },
  get payload() {
    return StepPayload;
  },
  timestamp: __t.timestamp(),
});
