// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DraftStep,
  TimerState,
} from "./types";


export default __t.row({
  lobbyId: __t.u32().primaryKey().name("lobby_id"),
  turnIndex: __t.u32().name("turn_index"),
  get draftSequence() {
    return __t.array(DraftStep).name("draft_sequence");
  },
  get timerState() {
    return TimerState.name("timer_state");
  },
  teamBlueBudget: __t.f32().name("team_blue_budget"),
  teamRedBudget: __t.f32().name("team_red_budget"),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
