// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  TeamSide,
  DraftStep,
  TimerState,
} from "./types";


export default __t.row({
  lobbyId: __t.u32().primaryKey().name("lobby_id"),
  turnIndex: __t.u32().name("turn_index"),
  get draftSequence() {
    return __t.array(DraftStep).name("draft_sequence");
  },
  get timerState() {
    return TimerState.name("timer_state");
  },
  isAuctionPhase: __t.bool().name("is_auction_phase"),
  get nextNominatorTeam() {
    return TeamSide.name("next_nominator_team");
  },
  blueCharactersWon: __t.u8().name("blue_characters_won"),
  redCharactersWon: __t.u8().name("red_characters_won"),
  currentNomination: __t.option(__t.string()).name("current_nomination"),
  currentBidAmount: __t.option(__t.f32()).name("current_bid_amount"),
  get currentBidTeam() {
    return TeamSide.name("current_bid_team");
  },
  teamBlueCharBudget: __t.f32().name("team_blue_char_budget"),
  teamRedCharBudget: __t.f32().name("team_red_char_budget"),
  teamBlueLcBudget: __t.f32().name("team_blue_lc_budget"),
  teamRedLcBudget: __t.f32().name("team_red_lc_budget"),
  pausesUsedBlue: __t.u8().name("pauses_used_blue"),
  pausesUsedRed: __t.u8().name("pauses_used_red"),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
