// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  GameMode,
  DraftMode,
  LobbyConfigSnapshot,
  MatchOutcome,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  lobbyCode: __t.string().name("lobby_code"),
  playedAt: __t.timestamp().name("played_at"),
  get draftMode() {
    return DraftMode.name("draft_mode");
  },
  get gameMode() {
    return GameMode.name("game_mode");
  },
  teamBlueAlias: __t.string().name("team_blue_alias"),
  teamRedAlias: __t.string().name("team_red_alias"),
  get snapshotConfig() {
    return LobbyConfigSnapshot.name("snapshot_config");
  },
  get outcome() {
    return MatchOutcome;
  },
  teamBlueSpent: __t.option(__t.f32()).name("team_blue_spent"),
  teamRedSpent: __t.option(__t.f32()).name("team_red_spent"),
  handicapApplied: __t.option(__t.f32()).name("handicap_applied"),
  isPubliclyVisible: __t.bool().name("is_publicly_visible"),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
