// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  GameMode,
  LobbyConfig,
  DraftMode,
  PlayerSnapshot,
  MatchResult,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  lobbyCode: __t.string().name("lobby_code"),
  playedAt: __t.timestamp().name("played_at"),
  get draftMode() {
    return DraftMode.name("draft_mode");
  },
  get gameMode() {
    return GameMode.name("game_mode");
  },
  teamBlueAlias: __t.string().name("team_blue_alias"),
  teamRedAlias: __t.string().name("team_red_alias"),
  get blueTeamMembers() {
    return __t.array(PlayerSnapshot).name("blue_team_members");
  },
  get redTeamMembers() {
    return __t.array(PlayerSnapshot).name("red_team_members");
  },
  get snapshotConfig() {
    return LobbyConfig.name("snapshot_config");
  },
  get result() {
    return MatchResult;
  },
  rosterBlue: __t.string().name("roster_blue"),
  rosterRed: __t.string().name("roster_red"),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
