// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ParticipantStatus,
} from "./types";


export default __t.row({
  tournamentId: __t.u32().name("tournament_id"),
  userId: __t.u32().name("user_id"),
  teamGroupId: __t.option(__t.u32()).name("team_group_id"),
  get status() {
    return ParticipantStatus;
  },
  anonymousAlias: __t.option(__t.string()).name("anonymous_alias"),
  isWaitlisted: __t.bool().name("is_waitlisted"),
  allowRandomTeamAssignment: __t.bool().name("allow_random_team_assignment"),
  approvedByToAt: __t.option(__t.timestamp()).name("approved_by_to_at"),
  hsrAccountId: __t.option(__t.u32()).name("hsr_account_id"),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
