// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  tournamentId: __t.u32().name("tournament_id"),
  userId: __t.u32().name("user_id"),
  canValidateResults: __t.bool().name("can_validate_results"),
  canOverrideResults: __t.bool().name("can_override_results"),
  canDqParticipants: __t.bool().name("can_dq_participants"),
  canManageBracket: __t.bool().name("can_manage_bracket"),
  canAssignSeeds: __t.bool().name("can_assign_seeds"),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
