// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  GameMode,
  TournamentFormat,
  TournamentStage,
  RosterVisibility,
  DisconnectPolicy,
  GroupAssignmentMode,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  name: __t.string(),
  description: __t.string(),
  organizerId: __t.u32().name("organizer_id"),
  get format() {
    return TournamentFormat;
  },
  get stage() {
    return TournamentStage;
  },
  get defaultGameMode() {
    return GameMode.name("default_game_mode");
  },
  maxParticipants: __t.u32().name("max_participants"),
  teamSize: __t.u8().name("team_size"),
  isAnonymousDefault: __t.bool().name("is_anonymous_default"),
  isAnonymousSpectators: __t.bool().name("is_anonymous_spectators"),
  get rosterVisibility() {
    return RosterVisibility.name("roster_visibility");
  },
  get disconnectPolicy() {
    return DisconnectPolicy.name("disconnect_policy");
  },
  checkInEnabled: __t.bool().name("check_in_enabled"),
  checkInPerRound: __t.bool().name("check_in_per_round"),
  autoForfeitEnabled: __t.bool().name("auto_forfeit_enabled"),
  autoForfeitMinutes: __t.u32().name("auto_forfeit_minutes"),
  bracketRevealAt: __t.option(__t.timestamp()).name("bracket_reveal_at"),
  winnerAdvantage: __t.u8().name("winner_advantage"),
  get groupAssignmentMode() {
    return GroupAssignmentMode.name("group_assignment_mode");
  },
  groupAdvanceCount: __t.u8().name("group_advance_count"),
  costSetId: __t.u32().name("cost_set_id"),
  seasonId: __t.option(__t.u32()).name("season_id"),
  countTowardsMmr: __t.bool().name("count_towards_mmr"),
  defaultBestOf: __t.u8().name("default_best_of"),
  requireVerified: __t.bool().name("require_verified"),
  requireRoster: __t.bool().name("require_roster"),
  minimumMmr: __t.option(__t.u32()).name("minimum_mmr"),
  requireApproval: __t.bool().name("require_approval"),
  waitlistEnabled: __t.bool().name("waitlist_enabled"),
  scheduledStartAt: __t.option(__t.timestamp()).name("scheduled_start_at"),
  registrationDeadline: __t.option(__t.timestamp()).name("registration_deadline"),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
