// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ParticipantType,
  ParticipantStatus,
} from "./types";


export default __t.row({
  tournamentId: __t.u32().name("tournament_id"),
  userId: __t.u32().name("user_id"),
  teamId: __t.option(__t.u32()).name("team_id"),
  get participantType() {
    return ParticipantType.name("participant_type");
  },
  get status() {
    return ParticipantStatus;
  },
  seedNumber: __t.option(__t.u32()).name("seed_number"),
  anonymousAlias: __t.option(__t.string()).name("anonymous_alias"),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
