// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AccountRatingConfig = __t.object("AccountRatingConfig", {
  id: __t.u32(),
  verticalWeight: __t.f64(),
  horizontalWeight: __t.f64(),
  compression: __t.f64(),
  roleExponentDps: __t.f64(),
  roleExponentSupport: __t.f64(),
  roleExponentSustain: __t.f64(),
  archetypeThreshold: __t.f64(),
  scale: __t.f64(),
  maxPossible: __t.f64(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type AccountRatingConfig = __Infer<typeof AccountRatingConfig>;

export const Achievement = __t.object("Achievement", {
  id: __t.u32(),
  name: __t.string(),
  description: __t.string(),
  get rarity() {
    return AchievementRarity;
  },
  isManualOnly: __t.bool(),
  maxAwards: __t.option(__t.u32()),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type Achievement = __Infer<typeof Achievement>;

export const AchievementCriteria = __t.object("AchievementCriteria", {
  id: __t.u32(),
  achievementId: __t.u32(),
  statTable: __t.string(),
  statField: __t.string(),
  get operator() {
    return ComparisonOperator;
  },
  thresholdValue: __t.u32(),
  filterGameMode: __t.option(__t.string()),
  filterCharacterName: __t.option(__t.string()),
  filterMatchType: __t.option(__t.string()),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type AchievementCriteria = __Infer<typeof AchievementCriteria>;

// The tagged union or sum type for the algebraic type `AchievementRarity`.
export const AchievementRarity = __t.enum("AchievementRarity", {
  Rare: __t.unit(),
  Epic: __t.unit(),
  Legendary: __t.unit(),
});
export type AchievementRarity = __Infer<typeof AchievementRarity>;

// The tagged union or sum type for the algebraic type `ActionType`.
export const ActionType = __t.enum("ActionType", {
  Pick: __t.unit(),
  Ban: __t.unit(),
  Nominate: __t.unit(),
  Bid: __t.unit(),
  AuctionSold: __t.unit(),
  Pause: __t.unit(),
  Undo: __t.unit(),
  EquipLightcone: __t.unit(),
  ArrangeLineup: __t.unit(),
  ConfirmLineup: __t.unit(),
});
export type ActionType = __Infer<typeof ActionType>;

export const AnonymousChatRow = __t.object("AnonymousChatRow", {
  id: __t.u32(),
  lobbyId: __t.u32(),
  senderUserId: __t.u32(),
  get senderType() {
    return ChatSenderType;
  },
  content: __t.string(),
  metadata: __t.option(__t.string()),
  anonymousLabel: __t.option(__t.string()),
  createdDate: __t.timestamp(),
});
export type AnonymousChatRow = __Infer<typeof AnonymousChatRow>;

export const AnonymousLobbyMemberRow = __t.object("AnonymousLobbyMemberRow", {
  lobbyId: __t.u32(),
  userId: __t.u32(),
  isOnline: __t.bool(),
  get lobbySlot() {
    return LobbySlot;
  },
  isReferee: __t.bool(),
  isConfirmed: __t.bool(),
  isCaptain: __t.bool(),
  displayName: __t.string(),
  anonymousLabel: __t.option(__t.string()),
});
export type AnonymousLobbyMemberRow = __Infer<typeof AnonymousLobbyMemberRow>;

export const AnonymousMatchParticipantRow = __t.object("AnonymousMatchParticipantRow", {
  matchResultId: __t.u32(),
  userId: __t.u32(),
  get teamSide() {
    return TeamSide;
  },
  isCaptain: __t.bool(),
  anonymousLabel: __t.option(__t.string()),
});
export type AnonymousMatchParticipantRow = __Infer<typeof AnonymousMatchParticipantRow>;

export const AnonymousMatchStepRow = __t.object("AnonymousMatchStepRow", {
  id: __t.u32(),
  lobbyId: __t.u32(),
  sequence: __t.u32(),
  actorUserId: __t.u32(),
  anonymousLabel: __t.option(__t.string()),
  get actorSlot() {
    return TeamSide;
  },
  get action() {
    return ActionType;
  },
  get payload() {
    return StepPayload;
  },
  timestamp: __t.timestamp(),
});
export type AnonymousMatchStepRow = __Infer<typeof AnonymousMatchStepRow>;

export const Archetype = __t.object("Archetype", {
  id: __t.u32(),
  name: __t.string(),
  description: __t.string(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type Archetype = __Infer<typeof Archetype>;

export const ArrangeLineupPayload = __t.object("ArrangeLineupPayload", {
  positions: __t.string(),
});
export type ArrangeLineupPayload = __Infer<typeof ArrangeLineupPayload>;

export const AuctionSoldPayload = __t.object("AuctionSoldPayload", {
  characterName: __t.string(),
  winningAmount: __t.f32(),
  get winningTeam() {
    return TeamSide;
  },
  eidolon: __t.u8(),
});
export type AuctionSoldPayload = __Infer<typeof AuctionSoldPayload>;

export const AvailabilitySlot = __t.object("AvailabilitySlot", {
  id: __t.u32(),
  userId: __t.u32(),
  startAt: __t.timestamp(),
  endAt: __t.timestamp(),
  isRecurring: __t.bool(),
  get recurrenceRule() {
    return RecurrenceRule;
  },
  expiresAt: __t.timestamp(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type AvailabilitySlot = __Infer<typeof AvailabilitySlot>;

// The tagged union or sum type for the algebraic type `BanMode`.
export const BanMode = __t.enum("BanMode", {
  None: __t.unit(),
  Four: __t.unit(),
  Six: __t.unit(),
});
export type BanMode = __Infer<typeof BanMode>;

export const BanPayload = __t.object("BanPayload", {
  characterName: __t.string(),
});
export type BanPayload = __Infer<typeof BanPayload>;

export const BanRecord = __t.object("BanRecord", {
  id: __t.u32(),
  get banType() {
    return BanType;
  },
  providerId: __t.string(),
  reason: __t.string(),
  bannedByUserId: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type BanRecord = __Infer<typeof BanRecord>;

// The tagged union or sum type for the algebraic type `BanType`.
export const BanType = __t.enum("BanType", {
  DiscordId: __t.unit(),
});
export type BanType = __Infer<typeof BanType>;

export const BidPayload = __t.object("BidPayload", {
  amount: __t.f32(),
  targetCharacter: __t.string(),
});
export type BidPayload = __Infer<typeof BidPayload>;

export const BracketMatch = __t.object("BracketMatch", {
  id: __t.u32(),
  tournamentId: __t.u32(),
  roundNumber: __t.u32(),
  matchNumber: __t.u32(),
  get bracketSide() {
    return BracketSide;
  },
  groupId: __t.option(__t.u32()),
  team1Id: __t.option(__t.u32()),
  team2Id: __t.option(__t.u32()),
  nextWinnerMatchId: __t.option(__t.u32()),
  nextLoserMatchId: __t.option(__t.u32()),
  bestOf: __t.u8(),
  get gameMode() {
    return GameMode;
  },
  winnerAdvantage: __t.u8(),
  scheduledAt: __t.option(__t.timestamp()),
  checkInRequired: __t.bool(),
  winnerTeamId: __t.option(__t.u32()),
  get resultStatus() {
    return MatchResultStatus;
  },
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type BracketMatch = __Infer<typeof BracketMatch>;

// The tagged union or sum type for the algebraic type `BracketSide`.
export const BracketSide = __t.enum("BracketSide", {
  Winners: __t.unit(),
  Losers: __t.unit(),
  GrandFinals: __t.unit(),
  ThirdPlace: __t.unit(),
  Group: __t.unit(),
});
export type BracketSide = __Infer<typeof BracketSide>;

export const CalendarEvent = __t.object("CalendarEvent", {
  id: __t.u32(),
  organizerId: __t.u32(),
  title: __t.string(),
  startAt: __t.timestamp(),
  endAt: __t.timestamp(),
  bracketMatchId: __t.option(__t.u32()),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
  description: __t.option(__t.string()),
});
export type CalendarEvent = __Infer<typeof CalendarEvent>;

export const CalendarEventInvite = __t.object("CalendarEventInvite", {
  eventId: __t.u32(),
  inviteeUserId: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
  get inviteStatus() {
    return InviteStatus;
  },
  respondedAt: __t.option(__t.timestamp()),
});
export type CalendarEventInvite = __Infer<typeof CalendarEventInvite>;

// The tagged union or sum type for the algebraic type `CharRole`.
export const CharRole = __t.enum("CharRole", {
  Dps: __t.unit(),
  Sustain: __t.unit(),
  Support: __t.unit(),
});
export type CharRole = __Infer<typeof CharRole>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u32(),
  lobbyId: __t.u32(),
  senderUserId: __t.u32(),
  get senderType() {
    return ChatSenderType;
  },
  content: __t.string(),
  metadata: __t.option(__t.string()),
  anonymousLabel: __t.option(__t.string()),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

// The tagged union or sum type for the algebraic type `ChatSenderType`.
export const ChatSenderType = __t.enum("ChatSenderType", {
  Player: __t.unit(),
  System: __t.unit(),
});
export type ChatSenderType = __Infer<typeof ChatSenderType>;

// The tagged union or sum type for the algebraic type `ComparisonOperator`.
export const ComparisonOperator = __t.enum("ComparisonOperator", {
  GreaterOrEqual: __t.unit(),
  GreaterThan: __t.unit(),
  Equal: __t.unit(),
  LessThan: __t.unit(),
  LessOrEqual: __t.unit(),
});
export type ComparisonOperator = __Infer<typeof ComparisonOperator>;

// The tagged union or sum type for the algebraic type `ConcedeTrigger`.
export const ConcedeTrigger = __t.enum("ConcedeTrigger", {
  Disconnect: __t.unit(),
  VoluntaryLeave: __t.unit(),
  RefereeDecision: __t.unit(),
});
export type ConcedeTrigger = __Infer<typeof ConcedeTrigger>;

export const ConfirmLineupPayload = __t.object("ConfirmLineupPayload", {
  confirmed: __t.bool(),
});
export type ConfirmLineupPayload = __Infer<typeof ConfirmLineupPayload>;

export const CostSet = __t.object("CostSet", {
  id: __t.u32(),
  name: __t.string(),
  creatorId: __t.u32(),
  get gameMode() {
    return GameMode;
  },
  isPublished: __t.bool(),
  isDraft: __t.bool(),
  isLocked: __t.bool(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type CostSet = __Infer<typeof CostSet>;

export const CostSetDraftCharacter = __t.object("CostSetDraftCharacter", {
  costSetId: __t.u32(),
  characterName: __t.string(),
  get gameMode() {
    return GameMode;
  },
  get draftMode() {
    return DraftMode;
  },
  get costs() {
    return EidolonCost;
  },
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type CostSetDraftCharacter = __Infer<typeof CostSetDraftCharacter>;

export const CostSetDraftLightcone = __t.object("CostSetDraftLightcone", {
  costSetId: __t.u32(),
  lightconeName: __t.string(),
  get gameMode() {
    return GameMode;
  },
  get draftMode() {
    return DraftMode;
  },
  get costs() {
    return SuperimpositionCost;
  },
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type CostSetDraftLightcone = __Infer<typeof CostSetDraftLightcone>;

export const CostSetDraftSynergy = __t.object("CostSetDraftSynergy", {
  costSetId: __t.u32(),
  sourceName: __t.string(),
  targetName: __t.string(),
  get gameMode() {
    return GameMode;
  },
  get draftMode() {
    return DraftMode;
  },
  costModifier: __t.f32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type CostSetDraftSynergy = __Infer<typeof CostSetDraftSynergy>;

export const DeletedUser = __t.object("DeletedUser", {
  id: __t.u32(),
  displayName: __t.string(),
  isGuest: __t.bool(),
  deletedAt: __t.timestamp(),
});
export type DeletedUser = __Infer<typeof DeletedUser>;

// The tagged union or sum type for the algebraic type `DisconnectPolicy`.
export const DisconnectPolicy = __t.enum("DisconnectPolicy", {
  Standard: __t.unit(),
  Deferred: __t.unit(),
  NoAction: __t.unit(),
});
export type DisconnectPolicy = __Infer<typeof DisconnectPolicy>;

// The tagged union or sum type for the algebraic type `DraftMode`.
export const DraftMode = __t.enum("DraftMode", {
  Classic: __t.unit(),
  Auction: __t.unit(),
});
export type DraftMode = __Infer<typeof DraftMode>;

export const DraftStep = __t.object("DraftStep", {
  get actionRequired() {
    return ActionType;
  },
  get teamTurn() {
    return TeamSide;
  },
});
export type DraftStep = __Infer<typeof DraftStep>;

export const EidolonCost = __t.object("EidolonCost", {
  e0: __t.f32(),
  e1: __t.f32(),
  e2: __t.f32(),
  e3: __t.f32(),
  e4: __t.f32(),
  e5: __t.f32(),
  e6: __t.f32(),
});
export type EidolonCost = __Infer<typeof EidolonCost>;

// The tagged union or sum type for the algebraic type `Element`.
export const Element = __t.enum("Element", {
  Fire: __t.unit(),
  Ice: __t.unit(),
  Imaginary: __t.unit(),
  Lightning: __t.unit(),
  Physical: __t.unit(),
  Quantum: __t.unit(),
  Wind: __t.unit(),
});
export type Element = __Infer<typeof Element>;

export const EloConfig = __t.object("EloConfig", {
  id: __t.u32(),
  kFactorNew: __t.u8(),
  kFactorMid: __t.u8(),
  kFactorVet: __t.u8(),
  newThreshold: __t.u32(),
  midThreshold: __t.u32(),
  initialRating: __t.u32(),
  sizeBonus: __t.u32(),
  spreadDivisor: __t.u8(),
  maxAccountBonus: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type EloConfig = __Infer<typeof EloConfig>;

export const EquipLightconePayload = __t.object("EquipLightconePayload", {
  characterName: __t.string(),
  lightconeName: __t.string(),
  superimposition: __t.u8(),
  costPaid: __t.f32(),
});
export type EquipLightconePayload = __Infer<typeof EquipLightconePayload>;

// The tagged union or sum type for the algebraic type `GameMode`.
export const GameMode = __t.enum("GameMode", {
  MemoryOfChaos: __t.unit(),
  ApocalypticShadow: __t.unit(),
  AnomalyArbitration: __t.unit(),
});
export type GameMode = __Infer<typeof GameMode>;

export const GcResult = __t.object("GcResult", {
  id: __t.u32(),
  gcType: __t.string(),
  ranAt: __t.timestamp(),
  itemsScanned: __t.u32(),
  itemsDeleted: __t.u32(),
  details: __t.string(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type GcResult = __Infer<typeof GcResult>;

export const GlobalCharacterStat = __t.object("GlobalCharacterStat", {
  characterName: __t.string(),
  get gameMode() {
    return GameMode;
  },
  get draftMode() {
    return DraftMode;
  },
  seasonId: __t.u32(),
  get matchType() {
    return MatchType;
  },
  teamSize: __t.u8(),
  timesPicked: __t.u32(),
  timesBanned: __t.u32(),
  wins: __t.u32(),
  losses: __t.u32(),
  matchesPlayed: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type GlobalCharacterStat = __Infer<typeof GlobalCharacterStat>;

// The tagged union or sum type for the algebraic type `GroupAssignmentMode`.
export const GroupAssignmentMode = __t.enum("GroupAssignmentMode", {
  Auto: __t.unit(),
  Manual: __t.unit(),
});
export type GroupAssignmentMode = __Infer<typeof GroupAssignmentMode>;

export const GroupPhaseRecord = __t.object("GroupPhaseRecord", {
  tournamentId: __t.u32(),
  groupId: __t.u32(),
  teamId: __t.u32(),
  wins: __t.u32(),
  losses: __t.u32(),
  draws: __t.u32(),
  points: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type GroupPhaseRecord = __Infer<typeof GroupPhaseRecord>;

export const HsrAccount = __t.object("HsrAccount", {
  id: __t.u32(),
  userId: __t.u32(),
  uid: __t.string(),
  region: __t.string(),
  displayLabel: __t.string(),
  isActive: __t.bool(),
  isRosterPublic: __t.bool(),
  isRatingPublic: __t.bool(),
  isDuplicateUid: __t.bool(),
  accountRating: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type HsrAccount = __Infer<typeof HsrAccount>;

export const HsrAccountCharacter = __t.object("HsrAccountCharacter", {
  hsrAccountId: __t.u32(),
  characterName: __t.string(),
  eidolonLevel: __t.u8(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type HsrAccountCharacter = __Infer<typeof HsrAccountCharacter>;

export const HsrCharacter = __t.object("HsrCharacter", {
  name: __t.string(),
  displayName: __t.string(),
  aliases: __t.array(__t.string()),
  rarity: __t.u8(),
  get path() {
    return Path;
  },
  get element() {
    return Element;
  },
  get role() {
    return CharRole;
  },
  imageUrl: __t.string(),
  versionReleased: __t.f64(),
  treatAsVersion: __t.f64(),
  skelUrl: __t.option(__t.string()),
  atlasUrl: __t.option(__t.string()),
  atlasImgUrls: __t.array(__t.string()),
  posX: __t.i32(),
  posY: __t.i32(),
  width: __t.i32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type HsrCharacter = __Infer<typeof HsrCharacter>;

export const HsrCharacterArchetype = __t.object("HsrCharacterArchetype", {
  characterName: __t.string(),
  archetypeId: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type HsrCharacterArchetype = __Infer<typeof HsrCharacterArchetype>;

export const HsrCharacterCost = __t.object("HsrCharacterCost", {
  characterName: __t.string(),
  get gameMode() {
    return GameMode;
  },
  get draftMode() {
    return DraftMode;
  },
  get costs() {
    return EidolonCost;
  },
  costSetId: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type HsrCharacterCost = __Infer<typeof HsrCharacterCost>;

export const HsrLightcone = __t.object("HsrLightcone", {
  name: __t.string(),
  displayName: __t.string(),
  aliases: __t.array(__t.string()),
  get path() {
    return Path;
  },
  rarity: __t.u8(),
  imageUrl: __t.string(),
  posX: __t.i32(),
  posY: __t.i32(),
  width: __t.i32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type HsrLightcone = __Infer<typeof HsrLightcone>;

export const HsrLightconeCost = __t.object("HsrLightconeCost", {
  lightconeName: __t.string(),
  get gameMode() {
    return GameMode;
  },
  get draftMode() {
    return DraftMode;
  },
  get costs() {
    return SuperimpositionCost;
  },
  costSetId: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type HsrLightconeCost = __Infer<typeof HsrLightconeCost>;

export const HsrSynergyCost = __t.object("HsrSynergyCost", {
  id: __t.u32(),
  sourceName: __t.string(),
  targetName: __t.string(),
  get gameMode() {
    return GameMode;
  },
  get draftMode() {
    return DraftMode;
  },
  costModifier: __t.f32(),
  costSetId: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type HsrSynergyCost = __Infer<typeof HsrSynergyCost>;

export const IdentityGcJob = __t.object("IdentityGcJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type IdentityGcJob = __Infer<typeof IdentityGcJob>;

// The tagged union or sum type for the algebraic type `InviteStatus`.
export const InviteStatus = __t.enum("InviteStatus", {
  Pending: __t.unit(),
  Accepted: __t.unit(),
  Declined: __t.unit(),
  Tentative: __t.unit(),
});
export type InviteStatus = __Infer<typeof InviteStatus>;

export const Leaderboard = __t.object("Leaderboard", {
  category: __t.string(),
  rank: __t.u16(),
  userId: __t.u32(),
  rating: __t.u32(),
  matchesPlayed: __t.u32(),
  wins: __t.u32(),
  seasonId: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type Leaderboard = __Infer<typeof Leaderboard>;

export const Lobby = __t.object("Lobby", {
  id: __t.u32(),
  joinCode: __t.string(),
  hostUserId: __t.u32(),
  teamBlueAlias: __t.string(),
  teamRedAlias: __t.string(),
  teamSize: __t.u8(),
  get draftMode() {
    return DraftMode;
  },
  get banMode() {
    return BanMode;
  },
  standardTurnSeconds: __t.u32(),
  reserveBankSeconds: __t.u32(),
  rosterDiffAdvantage: __t.f32(),
  rosterThreshold: __t.f32(),
  underThresholdAdvantage: __t.f32(),
  aboveThresholdPenalty: __t.f32(),
  deathPenalty: __t.f32(),
  get matchType() {
    return MatchType;
  },
  currentPlayerCount: __t.u8(),
  characterBudget: __t.f32(),
  lightconeBudget: __t.f32(),
  minimumBidRaise: __t.f32(),
  allowMirrorPicks: __t.bool(),
  autoRandomPick: __t.bool(),
  refereeCanUndo: __t.bool(),
  refereeCanPause: __t.bool(),
  refereeCanSetCaptain: __t.bool(),
  refereeCanKick: __t.bool(),
  allowPlayerPause: __t.bool(),
  refereeExclusiveConcede: __t.bool(),
  tournamentId: __t.option(__t.u32()),
  bracketMatchId: __t.option(__t.u32()),
  isTournamentControlled: __t.bool(),
  isAnonymousPlayers: __t.bool(),
  isAnonymousSpectators: __t.bool(),
  get rosterVisibility() {
    return RosterVisibility;
  },
  requireOwnership: __t.bool(),
  costSetId: __t.u32(),
  isPublic: __t.bool(),
  bestOf: __t.u8(),
  refereeControlsShelving: __t.bool(),
  get disconnectPolicy() {
    return DisconnectPolicy;
  },
  disconnectForfeitSeconds: __t.option(__t.u32()),
  get gameMode() {
    return GameMode;
  },
  lastActivityAt: __t.timestamp(),
  get stage() {
    return LobbyStage;
  },
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type Lobby = __Infer<typeof Lobby>;

export const LobbyBan = __t.object("LobbyBan", {
  lobbyId: __t.u32(),
  bannedUserId: __t.u32(),
  bannedByUserId: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type LobbyBan = __Infer<typeof LobbyBan>;

export const LobbyBrowserRow = __t.object("LobbyBrowserRow", {
  id: __t.u32(),
  joinCode: __t.string(),
  get gameMode() {
    return GameMode;
  },
  get draftMode() {
    return DraftMode;
  },
  get matchType() {
    return MatchType;
  },
  currentPlayerCount: __t.u8(),
  isTournamentControlled: __t.bool(),
  isAnonymousPlayers: __t.bool(),
  get stage() {
    return LobbyStage;
  },
  isPublic: __t.bool(),
  teamSize: __t.u8(),
  tournamentName: __t.option(__t.string()),
  costSetName: __t.option(__t.string()),
});
export type LobbyBrowserRow = __Infer<typeof LobbyBrowserRow>;

export const LobbyConfigSnapshot = __t.object("LobbyConfigSnapshot", {
  teamSize: __t.u8(),
  get draftMode() {
    return DraftMode;
  },
  get banMode() {
    return BanMode;
  },
  standardTurnSeconds: __t.u32(),
  reserveBankSeconds: __t.u32(),
  characterBudget: __t.f32(),
  lightconeBudget: __t.f32(),
  rosterDiffAdvantage: __t.f32(),
  rosterThreshold: __t.f32(),
  underThresholdAdvantage: __t.f32(),
  aboveThresholdPenalty: __t.f32(),
  deathPenalty: __t.f32(),
});
export type LobbyConfigSnapshot = __Infer<typeof LobbyConfigSnapshot>;

export const LobbyCursorEvent = __t.object("LobbyCursorEvent", {
  lobbyId: __t.u32(),
  senderUserId: __t.u32(),
  anonymousLabel: __t.option(__t.string()),
  x: __t.f32(),
  y: __t.f32(),
  timestamp: __t.timestamp(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type LobbyCursorEvent = __Infer<typeof LobbyCursorEvent>;

export const LobbyGcJob = __t.object("LobbyGcJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type LobbyGcJob = __Infer<typeof LobbyGcJob>;

export const LobbyMember = __t.object("LobbyMember", {
  lobbyId: __t.u32(),
  userId: __t.u32(),
  isOnline: __t.bool(),
  get lobbySlot() {
    return LobbySlot;
  },
  isReferee: __t.bool(),
  isConfirmed: __t.bool(),
  isCaptain: __t.bool(),
  voluntarilyLeft: __t.bool(),
  disconnectedAt: __t.option(__t.timestamp()),
  disconnectPoolRemainingMs: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type LobbyMember = __Infer<typeof LobbyMember>;

export const LobbyMemberAccount = __t.object("LobbyMemberAccount", {
  lobbyId: __t.u32(),
  userId: __t.u32(),
  hsrAccountId: __t.u32(),
});
export type LobbyMemberAccount = __Infer<typeof LobbyMemberAccount>;

export const LobbyPassword = __t.object("LobbyPassword", {
  lobbyId: __t.u32(),
  passwordHash: __t.string(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type LobbyPassword = __Infer<typeof LobbyPassword>;

export const LobbyPreset = __t.object("LobbyPreset", {
  id: __t.u32(),
  name: __t.string(),
  isSystemPreset: __t.bool(),
  creatorUserId: __t.u32(),
  teamSize: __t.u8(),
  get draftMode() {
    return DraftMode;
  },
  get banMode() {
    return BanMode;
  },
  get gameMode() {
    return GameMode;
  },
  get matchType() {
    return MatchType;
  },
  standardTurnSeconds: __t.u32(),
  reserveBankSeconds: __t.u32(),
  characterBudget: __t.f32(),
  lightconeBudget: __t.f32(),
  minimumBidRaise: __t.f32(),
  rosterDiffAdvantage: __t.f32(),
  rosterThreshold: __t.f32(),
  underThresholdAdvantage: __t.f32(),
  aboveThresholdPenalty: __t.f32(),
  deathPenalty: __t.f32(),
  isPublic: __t.bool(),
  isAnonymousPlayers: __t.bool(),
  isAnonymousSpectators: __t.bool(),
  get rosterVisibility() {
    return RosterVisibility;
  },
  requireOwnership: __t.bool(),
  costSetId: __t.u32(),
  get disconnectPolicy() {
    return DisconnectPolicy;
  },
  disconnectForfeitSeconds: __t.option(__t.u32()),
  allowMirrorPicks: __t.bool(),
  autoRandomPick: __t.bool(),
  refereeCanUndo: __t.bool(),
  refereeCanPause: __t.bool(),
  refereeCanSetCaptain: __t.bool(),
  refereeCanKick: __t.bool(),
  allowPlayerPause: __t.bool(),
  refereeExclusiveConcede: __t.bool(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type LobbyPreset = __Infer<typeof LobbyPreset>;

// The tagged union or sum type for the algebraic type `LobbySlot`.
export const LobbySlot = __t.enum("LobbySlot", {
  BluePlayer: __t.unit(),
  BlueCoach: __t.unit(),
  RedPlayer: __t.unit(),
  RedCoach: __t.unit(),
  Spectator: __t.unit(),
});
export type LobbySlot = __Infer<typeof LobbySlot>;

// The tagged union or sum type for the algebraic type `LobbyStage`.
export const LobbyStage = __t.enum("LobbyStage", {
  Waiting: __t.unit(),
  Drafting: __t.unit(),
  Equipping: __t.unit(),
  Scoring: __t.unit(),
  BetweenGames: __t.unit(),
  Shelved: __t.unit(),
  AwaitingResult: __t.unit(),
  Finished: __t.unit(),
});
export type LobbyStage = __Infer<typeof LobbyStage>;

// The tagged union or sum type for the algebraic type `MatchEndReason`.
export const MatchEndReason = __t.enum("MatchEndReason", {
  Completed: __t.unit(),
  Draw: __t.unit(),
  Concede: __t.unit(),
});
export type MatchEndReason = __Infer<typeof MatchEndReason>;

export const MatchParticipantHistory = __t.object("MatchParticipantHistory", {
  userId: __t.u32(),
  matchHistoryId: __t.u32(),
  get teamSide() {
    return TeamSide;
  },
  displayName: __t.string(),
  isReferee: __t.bool(),
  isCoach: __t.bool(),
  isCaptain: __t.bool(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type MatchParticipantHistory = __Infer<typeof MatchParticipantHistory>;

export const MatchResultGame = __t.object("MatchResultGame", {
  matchResultId: __t.u32(),
  gameNumber: __t.u8(),
  get gameMode() {
    return GameMode;
  },
  teamBlueScreenshotUrl: __t.option(__t.string()),
  teamRedScreenshotUrl: __t.option(__t.string()),
  teamBlueCyclesUsed: __t.option(__t.u32()),
  teamRedCyclesUsed: __t.option(__t.u32()),
  teamBlueScore: __t.option(__t.u64()),
  teamRedScore: __t.option(__t.u64()),
  teamBlueBoss1Score: __t.option(__t.u64()),
  teamBlueBoss2Score: __t.option(__t.u64()),
  teamRedBoss1Score: __t.option(__t.u64()),
  teamRedBoss2Score: __t.option(__t.u64()),
  get winnerTeamSide() {
    return TeamSide;
  },
  get validationStatus() {
    return ValidationStatus;
  },
  validatedByUserId: __t.option(__t.u32()),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type MatchResultGame = __Infer<typeof MatchResultGame>;

export const MatchResultGameHistory = __t.object("MatchResultGameHistory", {
  matchHistoryId: __t.u32(),
  gameNumber: __t.u8(),
  get gameMode() {
    return GameMode;
  },
  teamBlueScreenshotUrl: __t.option(__t.string()),
  teamRedScreenshotUrl: __t.option(__t.string()),
  teamBlueCyclesUsed: __t.option(__t.u32()),
  teamRedCyclesUsed: __t.option(__t.u32()),
  teamBlueScore: __t.option(__t.u64()),
  teamRedScore: __t.option(__t.u64()),
  teamBlueBoss1Score: __t.option(__t.u64()),
  teamBlueBoss2Score: __t.option(__t.u64()),
  teamRedBoss1Score: __t.option(__t.u64()),
  teamRedBoss2Score: __t.option(__t.u64()),
  get winnerTeamSide() {
    return TeamSide;
  },
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type MatchResultGameHistory = __Infer<typeof MatchResultGameHistory>;

export const MatchResultParticipant = __t.object("MatchResultParticipant", {
  matchResultId: __t.u32(),
  userId: __t.u32(),
  get teamSide() {
    return TeamSide;
  },
  isCaptain: __t.bool(),
  accountRatingSnapshot: __t.f64(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type MatchResultParticipant = __Infer<typeof MatchResultParticipant>;

export const MatchResultRecord = __t.object("MatchResultRecord", {
  id: __t.u32(),
  bracketMatchId: __t.option(__t.u32()),
  lobbyId: __t.u32(),
  isTournamentControlled: __t.bool(),
  get status() {
    return MatchResultStatus;
  },
  get winnerTeamSide() {
    return __t.option(TeamSide);
  },
  mmrProcessedAt: __t.option(__t.timestamp()),
  refereeUserId: __t.option(__t.u32()),
  disputedByUserId: __t.option(__t.u32()),
  disputeReason: __t.option(__t.string()),
  blueConfirmed: __t.bool(),
  redConfirmed: __t.bool(),
  refereeFullControl: __t.bool(),
  get matchType() {
    return MatchType;
  },
  get matchEndReason() {
    return __t.option(MatchEndReason);
  },
  get concedeTrigger() {
    return __t.option(ConcedeTrigger);
  },
  concedeSummary: __t.option(__t.string()),
  concedeAtStage: __t.option(__t.string()),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type MatchResultRecord = __Infer<typeof MatchResultRecord>;

// The tagged union or sum type for the algebraic type `MatchResultStatus`.
export const MatchResultStatus = __t.enum("MatchResultStatus", {
  Pending: __t.unit(),
  Submitted: __t.unit(),
  Disputed: __t.unit(),
  Validated: __t.unit(),
  Rejected: __t.unit(),
});
export type MatchResultStatus = __Infer<typeof MatchResultStatus>;

export const MatchSession = __t.object("MatchSession", {
  lobbyId: __t.u32(),
  turnIndex: __t.u32(),
  get draftSequence() {
    return __t.array(DraftStep);
  },
  get timerState() {
    return TimerState;
  },
  isAuctionPhase: __t.bool(),
  get nextNominatorTeam() {
    return TeamSide;
  },
  blueCharactersWon: __t.u8(),
  redCharactersWon: __t.u8(),
  currentNomination: __t.option(__t.string()),
  currentBidAmount: __t.option(__t.f32()),
  get currentBidTeam() {
    return TeamSide;
  },
  teamBlueCharBudget: __t.f32(),
  teamRedCharBudget: __t.f32(),
  teamBlueLcBudget: __t.f32(),
  teamRedLcBudget: __t.f32(),
  pausesUsedBlue: __t.u8(),
  pausesUsedRed: __t.u8(),
  currentGameNumber: __t.u8(),
  gamesWonBlue: __t.u8(),
  gamesWonRed: __t.u8(),
  seriesBestOf: __t.u8(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type MatchSession = __Infer<typeof MatchSession>;

export const MatchSessionHistory = __t.object("MatchSessionHistory", {
  id: __t.u32(),
  lobbyCode: __t.string(),
  playedAt: __t.timestamp(),
  get draftMode() {
    return DraftMode;
  },
  get gameMode() {
    return GameMode;
  },
  teamBlueAlias: __t.string(),
  teamRedAlias: __t.string(),
  get snapshotConfig() {
    return LobbyConfigSnapshot;
  },
  get outcome() {
    return MatchEndReason;
  },
  teamBlueSpent: __t.option(__t.f32()),
  teamRedSpent: __t.option(__t.f32()),
  handicapApplied: __t.option(__t.f32()),
  isPubliclyVisible: __t.bool(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type MatchSessionHistory = __Infer<typeof MatchSessionHistory>;

export const MatchSessionStep = __t.object("MatchSessionStep", {
  id: __t.u32(),
  lobbyId: __t.u32(),
  gameNumber: __t.u8(),
  sequence: __t.u32(),
  actorUserId: __t.u32(),
  anonymousLabel: __t.option(__t.string()),
  get actorSlot() {
    return TeamSide;
  },
  get action() {
    return ActionType;
  },
  get payload() {
    return StepPayload;
  },
  timestamp: __t.timestamp(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type MatchSessionStep = __Infer<typeof MatchSessionStep>;

export const MatchSessionStepHistory = __t.object("MatchSessionStepHistory", {
  matchHistoryId: __t.u32(),
  gameNumber: __t.u8(),
  sequence: __t.u32(),
  actorUserId: __t.u32(),
  actorDisplayName: __t.string(),
  get teamSide() {
    return TeamSide;
  },
  get action() {
    return ActionType;
  },
  targetName: __t.option(__t.string()),
  payload: __t.option(__t.string()),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type MatchSessionStepHistory = __Infer<typeof MatchSessionStepHistory>;

// The tagged union or sum type for the algebraic type `MatchType`.
export const MatchType = __t.enum("MatchType", {
  Casual: __t.unit(),
  Ranked: __t.unit(),
});
export type MatchType = __Infer<typeof MatchType>;

export const MmrHistory = __t.object("MmrHistory", {
  id: __t.u32(),
  userId: __t.u32(),
  get gameMode() {
    return GameMode;
  },
  matchHistoryId: __t.u32(),
  previousRating: __t.u32(),
  newRating: __t.u32(),
  delta: __t.i32(),
  seasonId: __t.option(__t.u32()),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type MmrHistory = __Infer<typeof MmrHistory>;

export const MmrRating = __t.object("MmrRating", {
  userId: __t.u32(),
  get gameMode() {
    return GameMode;
  },
  rating: __t.u32(),
  matchesPlayed: __t.u32(),
  globalCompositeRating: __t.option(__t.u32()),
  seasonId: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type MmrRating = __Infer<typeof MmrRating>;

export const MyProfileRow = __t.object("MyProfileRow", {
  id: __t.u32(),
  username: __t.string(),
  displayName: __t.string(),
  isGuest: __t.bool(),
  isOnline: __t.bool(),
  lastLoginAt: __t.timestamp(),
  get role() {
    return Role;
  },
  hasDiscordLinked: __t.bool(),
  avatarCharacterName: __t.string(),
  displayedAchievementId: __t.option(__t.u32()),
  deletedAt: __t.option(__t.timestamp()),
  discordId: __t.option(__t.string()),
  discordUsername: __t.option(__t.string()),
  email: __t.option(__t.string()),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type MyProfileRow = __Infer<typeof MyProfileRow>;

export const MyRosterAccountRow = __t.object("MyRosterAccountRow", {
  accountId: __t.u32(),
  uid: __t.string(),
  region: __t.string(),
  displayLabel: __t.string(),
  isActive: __t.bool(),
  isRosterPublic: __t.bool(),
  isRatingPublic: __t.bool(),
  isDuplicateUid: __t.bool(),
  accountRating: __t.u32(),
  characterName: __t.option(__t.string()),
  eidolonLevel: __t.option(__t.u8()),
});
export type MyRosterAccountRow = __Infer<typeof MyRosterAccountRow>;

export const NominatePayload = __t.object("NominatePayload", {
  characterName: __t.string(),
  eidolon: __t.u8(),
});
export type NominatePayload = __Infer<typeof NominatePayload>;

// The tagged union or sum type for the algebraic type `ParticipantStatus`.
export const ParticipantStatus = __t.enum("ParticipantStatus", {
  Registered: __t.unit(),
  CheckedIn: __t.unit(),
  Active: __t.unit(),
  Eliminated: __t.unit(),
  Disqualified: __t.unit(),
  Withdrawn: __t.unit(),
});
export type ParticipantStatus = __Infer<typeof ParticipantStatus>;

// The tagged union or sum type for the algebraic type `Path`.
export const Path = __t.enum("Path", {
  Abundance: __t.unit(),
  Destruction: __t.unit(),
  Erudition: __t.unit(),
  Harmony: __t.unit(),
  Hunt: __t.unit(),
  Nihility: __t.unit(),
  Preservation: __t.unit(),
  Remembrance: __t.unit(),
  Elation: __t.unit(),
});
export type Path = __Infer<typeof Path>;

export const PausePayload = __t.object("PausePayload", {
  timeRemainingMs: __t.u32(),
  isAutoPause: __t.bool(),
});
export type PausePayload = __Infer<typeof PausePayload>;

export const PickPayload = __t.object("PickPayload", {
  characterName: __t.string(),
  eidolon: __t.u8(),
  costPaid: __t.f32(),
});
export type PickPayload = __Infer<typeof PickPayload>;

export const PlayerCharacterStat = __t.object("PlayerCharacterStat", {
  userId: __t.u32(),
  characterName: __t.string(),
  get gameMode() {
    return GameMode;
  },
  get draftMode() {
    return DraftMode;
  },
  wins: __t.u32(),
  losses: __t.u32(),
  matchesPlayed: __t.u32(),
  seasonId: __t.u32(),
  get matchType() {
    return MatchType;
  },
  teamSize: __t.u8(),
  timesBannedInMatch: __t.u32(),
  timesFaced: __t.u32(),
  winsAgainst: __t.u32(),
  lossesAgainst: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type PlayerCharacterStat = __Infer<typeof PlayerCharacterStat>;

export const PlayerRelationship = __t.object("PlayerRelationship", {
  userId: __t.u32(),
  otherUserId: __t.u32(),
  get gameMode() {
    return GameMode;
  },
  get draftMode() {
    return DraftMode;
  },
  matchesAsAlly: __t.u32(),
  winsAsAlly: __t.u32(),
  matchesAsOpponent: __t.u32(),
  winsAsOpponent: __t.u32(),
  seasonId: __t.u32(),
  get matchType() {
    return MatchType;
  },
  teamSize: __t.u8(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type PlayerRelationship = __Infer<typeof PlayerRelationship>;

export const PlayerStat = __t.object("PlayerStat", {
  userId: __t.u32(),
  get gameMode() {
    return GameMode;
  },
  get draftMode() {
    return DraftMode;
  },
  matchesPlayed: __t.u32(),
  wins: __t.u32(),
  losses: __t.u32(),
  draws: __t.u32(),
  matchesSpectated: __t.u32(),
  seasonId: __t.u32(),
  get matchType() {
    return MatchType;
  },
  teamSize: __t.u8(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type PlayerStat = __Infer<typeof PlayerStat>;

export const PublicHsrAccountRow = __t.object("PublicHsrAccountRow", {
  accountId: __t.u32(),
  userId: __t.u32(),
  uid: __t.string(),
  region: __t.string(),
  displayLabel: __t.string(),
  accountRating: __t.option(__t.u32()),
  characterName: __t.option(__t.string()),
  eidolonLevel: __t.option(__t.u8()),
});
export type PublicHsrAccountRow = __Infer<typeof PublicHsrAccountRow>;

export const RecurrenceRule = __t.object("RecurrenceRule", {
  get recurrenceType() {
    return RecurrenceType;
  },
  interval: __t.u8(),
  dayOfWeek: __t.option(__t.u8()),
  dayOfMonth: __t.option(__t.u8()),
  endDate: __t.option(__t.timestamp()),
});
export type RecurrenceRule = __Infer<typeof RecurrenceRule>;

// The tagged union or sum type for the algebraic type `RecurrenceType`.
export const RecurrenceType = __t.enum("RecurrenceType", {
  Daily: __t.unit(),
  Weekly: __t.unit(),
  Monthly: __t.unit(),
});
export type RecurrenceType = __Infer<typeof RecurrenceType>;

// The tagged union or sum type for the algebraic type `Role`.
export const Role = __t.enum("Role", {
  Admin: __t.unit(),
  Moderator: __t.unit(),
  TournamentHost: __t.unit(),
  User: __t.unit(),
});
export type Role = __Infer<typeof Role>;

// The tagged union or sum type for the algebraic type `RosterVisibility`.
export const RosterVisibility = __t.enum("RosterVisibility", {
  OpenRoster: __t.unit(),
  ClosedWithRating: __t.unit(),
  ClosedNoRating: __t.unit(),
});
export type RosterVisibility = __Infer<typeof RosterVisibility>;

export const RosterVisibilityRow = __t.object("RosterVisibilityRow", {
  lobbyId: __t.u32(),
  memberUserId: __t.u32(),
  hsrAccountId: __t.u32(),
  characterName: __t.string(),
  eidolonLevel: __t.u8(),
  accountRating: __t.option(__t.u32()),
});
export type RosterVisibilityRow = __Infer<typeof RosterVisibilityRow>;

export const SavedCalendar = __t.object("SavedCalendar", {
  userId: __t.u32(),
  targetUserId: __t.u32(),
  isVisible: __t.bool(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type SavedCalendar = __Infer<typeof SavedCalendar>;

export const Season = __t.object("Season", {
  id: __t.u32(),
  name: __t.string(),
  startDate: __t.timestamp(),
  endDate: __t.option(__t.timestamp()),
  isActive: __t.bool(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type Season = __Infer<typeof Season>;

export const ServerIdentity = __t.object("ServerIdentity", {
  identity: __t.identity(),
  registeredAt: __t.timestamp(),
});
export type ServerIdentity = __Infer<typeof ServerIdentity>;

// The tagged union or sum type for the algebraic type `StepPayload`.
export const StepPayload = __t.enum("StepPayload", {
  get Pick() {
    return PickPayload;
  },
  get Ban() {
    return BanPayload;
  },
  get Bid() {
    return BidPayload;
  },
  get AuctionSold() {
    return AuctionSoldPayload;
  },
  get Nominate() {
    return NominatePayload;
  },
  get Undo() {
    return UndoPayload;
  },
  get Pause() {
    return PausePayload;
  },
  get EquipLightcone() {
    return EquipLightconePayload;
  },
  get ArrangeLineup() {
    return ArrangeLineupPayload;
  },
  get ConfirmLineup() {
    return ConfirmLineupPayload;
  },
});
export type StepPayload = __Infer<typeof StepPayload>;

export const SuperimpositionCost = __t.object("SuperimpositionCost", {
  s1: __t.f32(),
  s2: __t.f32(),
  s3: __t.f32(),
  s4: __t.f32(),
  s5: __t.f32(),
});
export type SuperimpositionCost = __Infer<typeof SuperimpositionCost>;

// The tagged union or sum type for the algebraic type `TeamSide`.
export const TeamSide = __t.enum("TeamSide", {
  Spectator: __t.unit(),
  Blue: __t.unit(),
  Red: __t.unit(),
});
export type TeamSide = __Infer<typeof TeamSide>;

export const TimerState = __t.object("TimerState", {
  turnStartAt: __t.timestamp(),
  teamBlueReserveMs: __t.u32(),
  teamRedReserveMs: __t.u32(),
  isPaused: __t.bool(),
  accumulatedPauseMs: __t.u32(),
});
export type TimerState = __Infer<typeof TimerState>;

export const Tournament = __t.object("Tournament", {
  id: __t.u32(),
  name: __t.string(),
  description: __t.string(),
  organizerId: __t.u32(),
  get format() {
    return TournamentFormat;
  },
  get stage() {
    return TournamentStage;
  },
  get defaultGameMode() {
    return GameMode;
  },
  maxParticipants: __t.u32(),
  teamSize: __t.u8(),
  isAnonymousDefault: __t.bool(),
  isAnonymousSpectators: __t.bool(),
  get rosterVisibility() {
    return RosterVisibility;
  },
  get disconnectPolicy() {
    return DisconnectPolicy;
  },
  checkInEnabled: __t.bool(),
  checkInPerRound: __t.bool(),
  autoForfeitEnabled: __t.bool(),
  autoForfeitMinutes: __t.u32(),
  bracketRevealAt: __t.option(__t.timestamp()),
  winnerAdvantage: __t.u8(),
  get groupAssignmentMode() {
    return GroupAssignmentMode;
  },
  groupAdvanceCount: __t.u8(),
  costSetId: __t.u32(),
  seasonId: __t.option(__t.u32()),
  countTowardsMmr: __t.bool(),
  defaultBestOf: __t.u8(),
  maxAccountsPerPlayer: __t.u8(),
  groupSize: __t.u8(),
  has3RdPlaceMatch: __t.bool(),
  autoAdvanceBracket: __t.bool(),
  requireOwnership: __t.bool(),
  requireVerified: __t.bool(),
  requireRoster: __t.bool(),
  minimumMmr: __t.option(__t.u32()),
  requireApproval: __t.bool(),
  waitlistEnabled: __t.bool(),
  scheduledStartAt: __t.option(__t.timestamp()),
  registrationDeadline: __t.option(__t.timestamp()),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type Tournament = __Infer<typeof Tournament>;

export const TournamentAssistant = __t.object("TournamentAssistant", {
  tournamentId: __t.u32(),
  userId: __t.u32(),
  canValidateResults: __t.bool(),
  canOverrideResults: __t.bool(),
  canDqParticipants: __t.bool(),
  canManageBracket: __t.bool(),
  canAssignSeeds: __t.bool(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type TournamentAssistant = __Infer<typeof TournamentAssistant>;

export const TournamentEnrolled = __t.object("TournamentEnrolled", {
  tournamentId: __t.u32(),
  userId: __t.u32(),
  get status() {
    return ParticipantStatus;
  },
  anonymousAlias: __t.option(__t.string()),
  isWaitlisted: __t.bool(),
  allowRandomTeamAssignment: __t.bool(),
  approvedByToAt: __t.option(__t.timestamp()),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type TournamentEnrolled = __Infer<typeof TournamentEnrolled>;

// The tagged union or sum type for the algebraic type `TournamentFormat`.
export const TournamentFormat = __t.enum("TournamentFormat", {
  SingleElimination: __t.unit(),
  DoubleElimination: __t.unit(),
  GroupOnly: __t.unit(),
  GroupIntoSingleElim: __t.unit(),
  GroupIntoDoubleElim: __t.unit(),
});
export type TournamentFormat = __Infer<typeof TournamentFormat>;

export const TournamentPlayerAccount = __t.object("TournamentPlayerAccount", {
  tournamentId: __t.u32(),
  userId: __t.u32(),
  hsrAccountId: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type TournamentPlayerAccount = __Infer<typeof TournamentPlayerAccount>;

export const TournamentRegistrantAccountRow = __t.object("TournamentRegistrantAccountRow", {
  tournamentId: __t.u32(),
  userId: __t.u32(),
  hsrAccountId: __t.u32(),
  displayLabel: __t.string(),
  accountRating: __t.option(__t.u32()),
  characterName: __t.option(__t.string()),
  eidolonLevel: __t.option(__t.u8()),
});
export type TournamentRegistrantAccountRow = __Infer<typeof TournamentRegistrantAccountRow>;

// The tagged union or sum type for the algebraic type `TournamentStage`.
export const TournamentStage = __t.enum("TournamentStage", {
  Draft: __t.unit(),
  Registration: __t.unit(),
  CheckIn: __t.unit(),
  Seeding: __t.unit(),
  InProgress: __t.unit(),
  Completed: __t.unit(),
  Cancelled: __t.unit(),
});
export type TournamentStage = __Infer<typeof TournamentStage>;

export const TournamentStandIn = __t.object("TournamentStandIn", {
  bracketMatchId: __t.u32(),
  userId: __t.u32(),
  approvedByUserId: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type TournamentStandIn = __Infer<typeof TournamentStandIn>;

export const TournamentTeam = __t.object("TournamentTeam", {
  id: __t.u32(),
  tournamentId: __t.u32(),
  name: __t.string(),
  captainUserId: __t.u32(),
  seedNumber: __t.option(__t.u32()),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type TournamentTeam = __Infer<typeof TournamentTeam>;

export const TournamentTeamMember = __t.object("TournamentTeamMember", {
  teamId: __t.u32(),
  userId: __t.u32(),
  tournamentId: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type TournamentTeamMember = __Infer<typeof TournamentTeamMember>;

export const TournamentTeamRequest = __t.object("TournamentTeamRequest", {
  teamId: __t.u32(),
  userId: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type TournamentTeamRequest = __Infer<typeof TournamentTeamRequest>;

export const UndoPayload = __t.object("UndoPayload", {
  originalSequenceId: __t.u32(),
});
export type UndoPayload = __Infer<typeof UndoPayload>;

export const User = __t.object("User", {
  id: __t.u32(),
  username: __t.string(),
  displayName: __t.string(),
  isGuest: __t.bool(),
  isOnline: __t.bool(),
  lastLoginAt: __t.timestamp(),
  get role() {
    return Role;
  },
  hasDiscordLinked: __t.bool(),
  avatarCharacterName: __t.string(),
  displayedAchievementId: __t.option(__t.u32()),
  deletedAt: __t.option(__t.timestamp()),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type User = __Infer<typeof User>;

export const UserAchievement = __t.object("UserAchievement", {
  id: __t.u32(),
  userId: __t.u32(),
  achievementId: __t.u32(),
  awardedById: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type UserAchievement = __Infer<typeof UserAchievement>;

export const UserDeletionJob = __t.object("UserDeletionJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  userId: __t.u32(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type UserDeletionJob = __Infer<typeof UserDeletionJob>;

export const UserIdentity = __t.object("UserIdentity", {
  identity: __t.identity(),
  userId: __t.u32(),
  lastSeenAt: __t.timestamp(),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type UserIdentity = __Infer<typeof UserIdentity>;

export const UserPrivate = __t.object("UserPrivate", {
  userId: __t.u32(),
  discordId: __t.option(__t.string()),
  discordUsername: __t.option(__t.string()),
  email: __t.option(__t.string()),
  createdById: __t.u32(),
  createdDate: __t.timestamp(),
  lastModifiedById: __t.u32(),
  lastModifiedDate: __t.timestamp(),
});
export type UserPrivate = __Infer<typeof UserPrivate>;

// The tagged union or sum type for the algebraic type `ValidationStatus`.
export const ValidationStatus = __t.enum("ValidationStatus", {
  Pending: __t.unit(),
  Confirmed: __t.unit(),
  Disputed: __t.unit(),
});
export type ValidationStatus = __Infer<typeof ValidationStatus>;

export const ViewAdminUserPrivate = __t.object("ViewAdminUserPrivate", {});
export type ViewAdminUserPrivate = __Infer<typeof ViewAdminUserPrivate>;

export const ViewLobbyBrowser = __t.object("ViewLobbyBrowser", {});
export type ViewLobbyBrowser = __Infer<typeof ViewLobbyBrowser>;

export const ViewMatchHistory = __t.object("ViewMatchHistory", {});
export type ViewMatchHistory = __Infer<typeof ViewMatchHistory>;

export const ViewMatchParticipantHistory = __t.object("ViewMatchParticipantHistory", {});
export type ViewMatchParticipantHistory = __Infer<typeof ViewMatchParticipantHistory>;

export const ViewMatchStepHistory = __t.object("ViewMatchStepHistory", {});
export type ViewMatchStepHistory = __Infer<typeof ViewMatchStepHistory>;

export const ViewMyCharacterStats = __t.object("ViewMyCharacterStats", {});
export type ViewMyCharacterStats = __Infer<typeof ViewMyCharacterStats>;

export const ViewMyCostSets = __t.object("ViewMyCostSets", {});
export type ViewMyCostSets = __Infer<typeof ViewMyCostSets>;

export const ViewMyDraftCharacterCosts = __t.object("ViewMyDraftCharacterCosts", {});
export type ViewMyDraftCharacterCosts = __Infer<typeof ViewMyDraftCharacterCosts>;

export const ViewMyDraftLightconeCosts = __t.object("ViewMyDraftLightconeCosts", {});
export type ViewMyDraftLightconeCosts = __Infer<typeof ViewMyDraftLightconeCosts>;

export const ViewMyDraftSynergyCosts = __t.object("ViewMyDraftSynergyCosts", {});
export type ViewMyDraftSynergyCosts = __Infer<typeof ViewMyDraftSynergyCosts>;

export const ViewMyIdentity = __t.object("ViewMyIdentity", {});
export type ViewMyIdentity = __Infer<typeof ViewMyIdentity>;

export const ViewMyLobbies = __t.object("ViewMyLobbies", {});
export type ViewMyLobbies = __Infer<typeof ViewMyLobbies>;

export const ViewMyLobbyChat = __t.object("ViewMyLobbyChat", {});
export type ViewMyLobbyChat = __Infer<typeof ViewMyLobbyChat>;

export const ViewMyLobbyMembers = __t.object("ViewMyLobbyMembers", {});
export type ViewMyLobbyMembers = __Infer<typeof ViewMyLobbyMembers>;

export const ViewMyMatchParticipantHistory = __t.object("ViewMyMatchParticipantHistory", {});
export type ViewMyMatchParticipantHistory = __Infer<typeof ViewMyMatchParticipantHistory>;

export const ViewMyMatchParticipants = __t.object("ViewMyMatchParticipants", {});
export type ViewMyMatchParticipants = __Infer<typeof ViewMyMatchParticipants>;

export const ViewMyMatchResultGameHistory = __t.object("ViewMyMatchResultGameHistory", {});
export type ViewMyMatchResultGameHistory = __Infer<typeof ViewMyMatchResultGameHistory>;

export const ViewMyMatchSessionHistory = __t.object("ViewMyMatchSessionHistory", {});
export type ViewMyMatchSessionHistory = __Infer<typeof ViewMyMatchSessionHistory>;

export const ViewMyMatchSessionStepHistory = __t.object("ViewMyMatchSessionStepHistory", {});
export type ViewMyMatchSessionStepHistory = __Infer<typeof ViewMyMatchSessionStepHistory>;

export const ViewMyMatchSteps = __t.object("ViewMyMatchSteps", {});
export type ViewMyMatchSteps = __Infer<typeof ViewMyMatchSteps>;

export const ViewMyMmrHistory = __t.object("ViewMyMmrHistory", {});
export type ViewMyMmrHistory = __Infer<typeof ViewMyMmrHistory>;

export const ViewMyPlayerStats = __t.object("ViewMyPlayerStats", {});
export type ViewMyPlayerStats = __Infer<typeof ViewMyPlayerStats>;

export const ViewMyProfile = __t.object("ViewMyProfile", {});
export type ViewMyProfile = __Infer<typeof ViewMyProfile>;

export const ViewMyRelationships = __t.object("ViewMyRelationships", {});
export type ViewMyRelationships = __Infer<typeof ViewMyRelationships>;

export const ViewMyRoster = __t.object("ViewMyRoster", {});
export type ViewMyRoster = __Infer<typeof ViewMyRoster>;

export const ViewMyRosterVisibility = __t.object("ViewMyRosterVisibility", {});
export type ViewMyRosterVisibility = __Infer<typeof ViewMyRosterVisibility>;

export const ViewMyTournamentEnrolled = __t.object("ViewMyTournamentEnrolled", {});
export type ViewMyTournamentEnrolled = __Infer<typeof ViewMyTournamentEnrolled>;

export const ViewMyTournamentGroupStandings = __t.object("ViewMyTournamentGroupStandings", {});
export type ViewMyTournamentGroupStandings = __Infer<typeof ViewMyTournamentGroupStandings>;

export const ViewMyTournamentLobbies = __t.object("ViewMyTournamentLobbies", {});
export type ViewMyTournamentLobbies = __Infer<typeof ViewMyTournamentLobbies>;

export const ViewMyTournamentMatchResults = __t.object("ViewMyTournamentMatchResults", {});
export type ViewMyTournamentMatchResults = __Infer<typeof ViewMyTournamentMatchResults>;

export const ViewMyTournamentMatches = __t.object("ViewMyTournamentMatches", {});
export type ViewMyTournamentMatches = __Infer<typeof ViewMyTournamentMatches>;

export const ViewMyTournamentTeamMembers = __t.object("ViewMyTournamentTeamMembers", {});
export type ViewMyTournamentTeamMembers = __Infer<typeof ViewMyTournamentTeamMembers>;

export const ViewMyTournamentTeams = __t.object("ViewMyTournamentTeams", {});
export type ViewMyTournamentTeams = __Infer<typeof ViewMyTournamentTeams>;

export const ViewMyTournaments = __t.object("ViewMyTournaments", {});
export type ViewMyTournaments = __Infer<typeof ViewMyTournaments>;

export const ViewPublicHsrAccounts = __t.object("ViewPublicHsrAccounts", {});
export type ViewPublicHsrAccounts = __Infer<typeof ViewPublicHsrAccounts>;

export const ViewTournamentRegistrantAccounts = __t.object("ViewTournamentRegistrantAccounts", {});
export type ViewTournamentRegistrantAccounts = __Infer<typeof ViewTournamentRegistrantAccounts>;

