// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import { AchievementRarity } from "./types";

export default {
  achievementId: __t.u32(),
  name: __t.option(__t.string()),
  description: __t.option(__t.string()),
  get rarity() {
    return AchievementRarity;
  },
};
