// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  slotId: __t.u32(),
  startAt: __t.string(),
  endAt: __t.string(),
  isRecurring: __t.bool(),
  recurrenceType: __t.string(),
  interval: __t.u8(),
  dayOfWeek: __t.u8(),
  dayOfMonth: __t.u8(),
  endDate: __t.string(),
};
