// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  tournamentId: __t.u32(),
  name: __t.string(),
  description: __t.string(),
  rosterVisibility: __t.string(),
  isAnonymousDefault: __t.bool(),
  disconnectPolicy: __t.string(),
  costSetId: __t.u32(),
  defaultBestOf: __t.u8(),
  groupSize: __t.u8(),
  has3RdPlaceMatch: __t.bool(),
  autoAdvanceBracket: __t.bool(),
  winnerAdvantage: __t.u8(),
  requireVerified: __t.bool(),
  requireRoster: __t.bool(),
  minimumMmr: __t.u32(),
  requireApproval: __t.bool(),
  waitlistEnabled: __t.bool(),
  scheduledStartAt: __t.string(),
  registrationDeadline: __t.string(),
};
