// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  accountId: __t.u32().name("account_id"),
  uid: __t.string(),
  region: __t.string(),
  displayLabel: __t.string().name("display_label"),
  isActive: __t.bool().name("is_active"),
  isRosterPublic: __t.bool().name("is_roster_public"),
  isRatingPublic: __t.bool().name("is_rating_public"),
  isDuplicateUid: __t.bool().name("is_duplicate_uid"),
  accountRating: __t.u32().name("account_rating"),
  characterName: __t.option(__t.string()).name("character_name"),
  eidolonLevel: __t.option(__t.u8()).name("eidolon_level"),
});
