// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import { GameMode, DraftMode, SuperimpositionCost } from "./types";

export default __t.row({
  costSetId: __t.u32().name("cost_set_id"),
  lightconeName: __t.string().name("lightcone_name"),
  get gameMode() {
    return GameMode.name("game_mode");
  },
  get draftMode() {
    return DraftMode.name("draft_mode");
  },
  get costs() {
    return SuperimpositionCost;
  },
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
