// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import { TeamSide } from "./types";

export default __t.row({
  userId: __t.u32().name("user_id"),
  matchHistoryId: __t.u32().name("match_history_id"),
  get teamSide() {
    return TeamSide.name("team_side");
  },
  displayName: __t.string().name("display_name"),
  isReferee: __t.bool().name("is_referee"),
  isCoach: __t.bool().name("is_coach"),
  isCaptain: __t.bool().name("is_captain"),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
