// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import { Role } from "./types";

export default __t.row({
  id: __t.u32(),
  username: __t.string(),
  displayName: __t.string().name("display_name"),
  get role() {
    return Role;
  },
  avatarCharacterName: __t.string().name("avatar_character_name"),
  isOnline: __t.bool().name("is_online"),
  isGuest: __t.bool().name("is_guest"),
  hasDiscordLinked: __t.bool().name("has_discord_linked"),
  displayedAchievementId: __t
    .option(__t.u32())
    .name("displayed_achievement_id"),
});
