// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import { GameMode, DraftMode, MatchType, LobbyStage } from "./types";

export default __t.row({
  id: __t.u32(),
  joinCode: __t.string().name("join_code"),
  get gameMode() {
    return GameMode.name("game_mode");
  },
  get draftMode() {
    return DraftMode.name("draft_mode");
  },
  get matchType() {
    return MatchType.name("match_type");
  },
  currentPlayerCount: __t.u8().name("current_player_count"),
  isTournamentControlled: __t.bool().name("is_tournament_controlled"),
  isAnonymousPlayers: __t.bool().name("is_anonymous_players"),
  get stage() {
    return LobbyStage;
  },
  isPublic: __t.bool().name("is_public"),
  teamSize: __t.u8().name("team_size"),
  tournamentName: __t.option(__t.string()).name("tournament_name"),
  costSetName: __t.option(__t.string()).name("cost_set_name"),
});
