// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import { LobbySlot } from "./types";

export default __t.row({
  lobbyId: __t.u32().name("lobby_id"),
  userId: __t.u32().name("user_id"),
  isOnline: __t.bool().name("is_online"),
  get lobbySlot() {
    return LobbySlot.name("lobby_slot");
  },
  isReferee: __t.bool().name("is_referee"),
  isConfirmed: __t.bool().name("is_confirmed"),
  isCaptain: __t.bool().name("is_captain"),
  displayName: __t.string().name("display_name"),
  anonymousLabel: __t.option(__t.string()).name("anonymous_label"),
});
