// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import { GameMode, DraftMode, MatchType } from "./types";

export default __t.row({
  userId: __t.u32().name("user_id"),
  get gameMode() {
    return GameMode.name("game_mode");
  },
  get draftMode() {
    return DraftMode.name("draft_mode");
  },
  matchesPlayed: __t.u32().name("matches_played"),
  wins: __t.u32(),
  losses: __t.u32(),
  draws: __t.u32(),
  matchesSpectated: __t.u32().name("matches_spectated"),
  seasonId: __t.u32().name("season_id"),
  get matchType() {
    return MatchType.name("match_type");
  },
  teamSize: __t.u8().name("team_size"),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
