// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  tournamentId: __t.u32().name("tournament_id"),
  userId: __t.u32().name("user_id"),
  hsrAccountId: __t.u32().name("hsr_account_id"),
  displayLabel: __t.string().name("display_label"),
  accountRating: __t.option(__t.u32()).name("account_rating"),
  characterName: __t.option(__t.string()).name("character_name"),
  eidolonLevel: __t.option(__t.u8()).name("eidolon_level"),
});
