// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import { ChatSenderType } from "./types";

export default __t.row({
  id: __t.u32(),
  lobbyId: __t.u32().name("lobby_id"),
  senderUserId: __t.u32().name("sender_user_id"),
  get senderType() {
    return ChatSenderType.name("sender_type");
  },
  content: __t.string(),
  metadata: __t.option(__t.string()),
  anonymousLabel: __t.option(__t.string()).name("anonymous_label"),
  createdDate: __t.timestamp().name("created_date"),
});
