// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import { TeamSide, ActionType } from "./types";

export default __t.row({
  matchHistoryId: __t.u32().name("match_history_id"),
  gameNumber: __t.u8().name("game_number"),
  sequence: __t.u32(),
  actorUserId: __t.u32().name("actor_user_id"),
  actorDisplayName: __t.string().name("actor_display_name"),
  get teamSide() {
    return TeamSide.name("team_side");
  },
  get action() {
    return ActionType;
  },
  targetName: __t.option(__t.string()).name("target_name"),
  payload: __t.option(__t.string()),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
