// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BroadcastCursorReducer from "../broadcast_cursor_reducer";
import DeleteGuestAccountReducer from "../delete_guest_account_reducer";
import LoginAsGuestReducer from "../login_as_guest_reducer";
import RegisterServerReducer from "../register_server_reducer";
import ServerLinkDiscordReducer from "../server_link_discord_reducer";
import ServerPromoteAdminReducer from "../server_promote_admin_reducer";
import UpdateAvatarReducer from "../update_avatar_reducer";
import UpdateDisplayNameReducer from "../update_display_name_reducer";
import UpdateUsernameReducer from "../update_username_reducer";

export type BroadcastCursorParams = __Infer<typeof BroadcastCursorReducer>;
export type DeleteGuestAccountParams = __Infer<typeof DeleteGuestAccountReducer>;
export type LoginAsGuestParams = __Infer<typeof LoginAsGuestReducer>;
export type RegisterServerParams = __Infer<typeof RegisterServerReducer>;
export type ServerLinkDiscordParams = __Infer<typeof ServerLinkDiscordReducer>;
export type ServerPromoteAdminParams = __Infer<typeof ServerPromoteAdminReducer>;
export type UpdateAvatarParams = __Infer<typeof UpdateAvatarReducer>;
export type UpdateDisplayNameParams = __Infer<typeof UpdateDisplayNameReducer>;
export type UpdateUsernameParams = __Infer<typeof UpdateUsernameReducer>;

