// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdminAssignCharacterArchetypesReducer from "../admin_assign_character_archetypes_reducer";
import AdminBatchRemoveCharactersReducer from "../admin_batch_remove_characters_reducer";
import AdminBatchUpsertCharactersReducer from "../admin_batch_upsert_characters_reducer";
import AdminBulkUpsertReducer from "../admin_bulk_upsert_reducer";
import AdminCreateHsrAccountReducer from "../admin_create_hsr_account_reducer";
import AdminDeleteArchetypeReducer from "../admin_delete_archetype_reducer";
import AdminDeleteHsrAccountReducer from "../admin_delete_hsr_account_reducer";
import AdminDeleteRowReducer from "../admin_delete_row_reducer";
import AdminRemoveCharacterArchetypesReducer from "../admin_remove_character_archetypes_reducer";
import AdminUpdateHsrAccountReducer from "../admin_update_hsr_account_reducer";
import AdminUpdateUserReducer from "../admin_update_user_reducer";
import AdminUpsertArchetypeReducer from "../admin_upsert_archetype_reducer";
import BatchRemoveCharactersReducer from "../batch_remove_characters_reducer";
import BatchUpsertCharactersReducer from "../batch_upsert_characters_reducer";
import BroadcastCursorReducer from "../broadcast_cursor_reducer";
import CreateHsrAccountReducer from "../create_hsr_account_reducer";
import DeleteGuestAccountReducer from "../delete_guest_account_reducer";
import DeleteHsrAccountReducer from "../delete_hsr_account_reducer";
import LoginAsGuestReducer from "../login_as_guest_reducer";
import MigrateRosterReducer from "../migrate_roster_reducer";
import RegisterServerReducer from "../register_server_reducer";
import ServerDeleteUserReducer from "../server_delete_user_reducer";
import ServerLinkDiscordReducer from "../server_link_discord_reducer";
import ServerSetRoleReducer from "../server_set_role_reducer";
import SetActiveHsrAccountReducer from "../set_active_hsr_account_reducer";
import UpdateAvatarReducer from "../update_avatar_reducer";
import UpdateDisplayNameReducer from "../update_display_name_reducer";
import UpdateHsrAccountReducer from "../update_hsr_account_reducer";
import UpdateUsernameReducer from "../update_username_reducer";

export type AdminAssignCharacterArchetypesParams = __Infer<typeof AdminAssignCharacterArchetypesReducer>;
export type AdminBatchRemoveCharactersParams = __Infer<typeof AdminBatchRemoveCharactersReducer>;
export type AdminBatchUpsertCharactersParams = __Infer<typeof AdminBatchUpsertCharactersReducer>;
export type AdminBulkUpsertParams = __Infer<typeof AdminBulkUpsertReducer>;
export type AdminCreateHsrAccountParams = __Infer<typeof AdminCreateHsrAccountReducer>;
export type AdminDeleteArchetypeParams = __Infer<typeof AdminDeleteArchetypeReducer>;
export type AdminDeleteHsrAccountParams = __Infer<typeof AdminDeleteHsrAccountReducer>;
export type AdminDeleteRowParams = __Infer<typeof AdminDeleteRowReducer>;
export type AdminRemoveCharacterArchetypesParams = __Infer<typeof AdminRemoveCharacterArchetypesReducer>;
export type AdminUpdateHsrAccountParams = __Infer<typeof AdminUpdateHsrAccountReducer>;
export type AdminUpdateUserParams = __Infer<typeof AdminUpdateUserReducer>;
export type AdminUpsertArchetypeParams = __Infer<typeof AdminUpsertArchetypeReducer>;
export type BatchRemoveCharactersParams = __Infer<typeof BatchRemoveCharactersReducer>;
export type BatchUpsertCharactersParams = __Infer<typeof BatchUpsertCharactersReducer>;
export type BroadcastCursorParams = __Infer<typeof BroadcastCursorReducer>;
export type CreateHsrAccountParams = __Infer<typeof CreateHsrAccountReducer>;
export type DeleteGuestAccountParams = __Infer<typeof DeleteGuestAccountReducer>;
export type DeleteHsrAccountParams = __Infer<typeof DeleteHsrAccountReducer>;
export type LoginAsGuestParams = __Infer<typeof LoginAsGuestReducer>;
export type MigrateRosterParams = __Infer<typeof MigrateRosterReducer>;
export type RegisterServerParams = __Infer<typeof RegisterServerReducer>;
export type ServerDeleteUserParams = __Infer<typeof ServerDeleteUserReducer>;
export type ServerLinkDiscordParams = __Infer<typeof ServerLinkDiscordReducer>;
export type ServerSetRoleParams = __Infer<typeof ServerSetRoleReducer>;
export type SetActiveHsrAccountParams = __Infer<typeof SetActiveHsrAccountReducer>;
export type UpdateAvatarParams = __Infer<typeof UpdateAvatarReducer>;
export type UpdateDisplayNameParams = __Infer<typeof UpdateDisplayNameReducer>;
export type UpdateHsrAccountParams = __Infer<typeof UpdateHsrAccountReducer>;
export type UpdateUsernameParams = __Infer<typeof UpdateUsernameReducer>;

