/**
 * Server-side SpacetimeDB connection singleton.
 * Used by Next.js API routes to call trusted reducers (e.g. server_link_provider).
 *
 * The connection authenticates with SPACETIMEDB_SERVER_TOKEN from .env.local,
 * which was generated by the scripts/register-server.ts setup script.
 */
import { DbConnection } from '../src/module_bindings';

// Ensure wss:// protocol — .env.local may use https://
let HOST = process.env.SPACETIMEDB_HOST ?? 'wss://maincloud.spacetimedb.com';
if (HOST.startsWith('https://')) HOST = HOST.replace('https://', 'wss://');
else if (HOST.startsWith('http://')) HOST = HOST.replace('http://', 'ws://');

const DB_NAME = process.env.SPACETIMEDB_DB_NAME ?? 'nextjs-ts';
const SERVER_TOKEN = process.env.SPACETIMEDB_SERVER_TOKEN;

let connectionPromise: Promise<DbConnection> | null = null;

/**
 * Returns the singleton server-side SpacetimeDB connection.
 * Lazily connects on first call, reuses on subsequent calls.
 */
export function getServerConnection(): Promise<DbConnection> {
    if (connectionPromise) return connectionPromise;

    if (!SERVER_TOKEN) {
        return Promise.reject(
            new Error('SPACETIMEDB_SERVER_TOKEN not set. Run: npx tsx scripts/register-server.ts')
        );
    }

    connectionPromise = new Promise<DbConnection>((resolve, reject) => {
        // build() initiates the WebSocket — keep reference to prevent GC
        const _conn = DbConnection.builder()
            .withUri(HOST)
            .withDatabaseName(DB_NAME)
            .withToken(SERVER_TOKEN)
            .onConnect((connection) => {
                console.log('[SpacetimeDB Server] Connected as server identity');
                resolve(connection);
            })
            .onConnectError((_ctx, err) => {
                console.error('[SpacetimeDB Server] Connection failed:', err);
                connectionPromise = null; // Allow retry
                reject(err);
            })
            .onDisconnect(() => {
                console.log('[SpacetimeDB Server] Disconnected');
                connectionPromise = null; // Allow reconnect
            })
            .build();
    });

    return connectionPromise;
}

/**
 * Verify a client's identity by creating an ephemeral SpacetimeDB connection
 * using the client's auth token. Extracts the server-verified identity from
 * onConnect, then immediately disconnects. (D-09, WR-02)
 *
 * This replaces the previous approach of trusting client-supplied identity hex.
 */
export function verifyIdentityFromToken(clientToken: string): Promise<string> {
    return new Promise<string>((resolve, reject) => {
        const timeout = setTimeout(() => {
            reject(new Error('Ephemeral connection timeout (5s)'));
        }, 5000);

        let resolved = false;

        DbConnection.builder()
            .withUri(HOST)
            .withDatabaseName(DB_NAME)
            .withToken(clientToken)
            .onConnect((_conn, identity) => {
                if (resolved) return;
                resolved = true;
                clearTimeout(timeout);
                _conn.disconnect();
                resolve(identity.toHexString());
            })
            .onConnectError((_ctx, err) => {
                if (resolved) return;
                resolved = true;
                clearTimeout(timeout);
                reject(new Error(`Ephemeral connection failed: ${err}`));
            })
            .onDisconnect(() => {
                // WR-02: Fail fast on disconnect instead of waiting for timeout
                if (resolved) return;
                resolved = true;
                clearTimeout(timeout);
                reject(new Error('Ephemeral connection disconnected before identity resolved'));
            })
            .build();
    });
}
