/**
 * Server-side SpacetimeDB connection singleton.
 * Used by Next.js API routes to call trusted reducers (e.g. server_link_discord).
 *
 * The connection authenticates with SPACETIMEDB_SERVER_TOKEN from .env.local,
 * which was generated by the scripts/register-server.ts setup script.
 */
import { DbConnection } from '../src/module_bindings';

// Ensure wss:// protocol — .env.local may use https://
let HOST = process.env.SPACETIMEDB_HOST ?? 'wss://maincloud.spacetimedb.com';
if (HOST.startsWith('https://')) HOST = HOST.replace('https://', 'wss://');
else if (HOST.startsWith('http://')) HOST = HOST.replace('http://', 'ws://');

const DB_NAME = process.env.SPACETIMEDB_DB_NAME ?? 'nextjs-ts';
const SERVER_TOKEN = process.env.SPACETIMEDB_SERVER_TOKEN;

let connectionPromise: Promise<DbConnection> | null = null;

/**
 * Returns the singleton server-side SpacetimeDB connection.
 * Lazily connects on first call, reuses on subsequent calls.
 */
export function getServerConnection(): Promise<DbConnection> {
    if (connectionPromise) return connectionPromise;

    if (!SERVER_TOKEN) {
        return Promise.reject(
            new Error('SPACETIMEDB_SERVER_TOKEN not set. Run: npx tsx scripts/register-server.ts')
        );
    }

    connectionPromise = new Promise<DbConnection>((resolve, reject) => {
        // build() initiates the WebSocket — keep reference to prevent GC
        const _conn = DbConnection.builder()
            .withUri(HOST)
            .withDatabaseName(DB_NAME)
            .withToken(SERVER_TOKEN)
            .onConnect((connection) => {
                console.log('[SpacetimeDB Server] Connected as server identity');
                resolve(connection);
            })
            .onConnectError((_ctx, err) => {
                console.error('[SpacetimeDB Server] Connection failed:', err);
                connectionPromise = null; // Allow retry
                reject(err);
            })
            .onDisconnect(() => {
                console.log('[SpacetimeDB Server] Disconnected');
                connectionPromise = null; // Allow reconnect
            })
            .build();
    });

    return connectionPromise;
}
