// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  verticalWeight: __t.f64().name("vertical_weight"),
  horizontalWeight: __t.f64().name("horizontal_weight"),
  compression: __t.f64(),
  roleExponentDps: __t.f64().name("role_exponent_dps"),
  roleExponentSupport: __t.f64().name("role_exponent_support"),
  roleExponentSustain: __t.f64().name("role_exponent_sustain"),
  archetypeThreshold: __t.f64().name("archetype_threshold"),
  scale: __t.f64(),
  maxPossible: __t.f64().name("max_possible"),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
