// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ComparisonOperator,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  achievementId: __t.u32().name("achievement_id"),
  statTable: __t.string().name("stat_table"),
  statField: __t.string().name("stat_field"),
  get operator() {
    return ComparisonOperator;
  },
  thresholdValue: __t.u32().name("threshold_value"),
  filterGameMode: __t.option(__t.string()).name("filter_game_mode"),
  filterCharacterName: __t.option(__t.string()).name("filter_character_name"),
  filterMatchType: __t.option(__t.string()).name("filter_match_type"),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
