// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  kFactorNew: __t.option(__t.u8()),
  kFactorMid: __t.option(__t.u8()),
  kFactorVet: __t.option(__t.u8()),
  newThreshold: __t.option(__t.u32()),
  midThreshold: __t.option(__t.u32()),
  initialRating: __t.option(__t.u32()),
  sizeBonus: __t.option(__t.u32()),
  spreadDivisor: __t.option(__t.u8()),
  maxAccountBonus: __t.option(__t.u32()),
};
