// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  lobbyId: __t.u32().name("lobby_id"),
  senderUserId: __t.u32().name("sender_user_id"),
  anonymousLabel: __t.option(__t.string()).name("anonymous_label"),
  x: __t.f32(),
  y: __t.f32(),
  timestamp: __t.timestamp(),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
