// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  GameMode,
} from "./types";


export default __t.row({
  userId: __t.u32().name("user_id"),
  get gameMode() {
    return GameMode.name("game_mode");
  },
  rating: __t.u32(),
  matchesPlayed: __t.u32().name("matches_played"),
  globalCompositeRating: __t.option(__t.u32()).name("global_composite_rating"),
  seasonId: __t.u32().name("season_id"),
  createdById: __t.u32().name("created_by_id"),
  createdDate: __t.timestamp().name("created_date"),
  lastModifiedById: __t.u32().name("last_modified_by_id"),
  lastModifiedDate: __t.timestamp().name("last_modified_date"),
});
