// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  matchResultId: __t.u32(),
  gameNumber: __t.u8(),
  winnerTeamSide: __t.string(),
  teamBlueCyclesUsed: __t.option(__t.u32()),
  teamRedCyclesUsed: __t.option(__t.u32()),
  teamBlueScore: __t.option(__t.u64()),
  teamRedScore: __t.option(__t.u64()),
  teamBlueBoss1Score: __t.option(__t.u64()),
  teamBlueBoss2Score: __t.option(__t.u64()),
  teamRedBoss1Score: __t.option(__t.u64()),
  teamRedBoss2Score: __t.option(__t.u64()),
  teamBlueScreenshotUrl: __t.option(__t.string()),
  teamRedScreenshotUrl: __t.option(__t.string()),
};
