// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  lobbyId: __t.u32().name("lobby_id"),
  memberUserId: __t.u32().name("member_user_id"),
  hsrAccountId: __t.u32().name("hsr_account_id"),
  characterName: __t.string().name("character_name"),
  eidolonLevel: __t.u8().name("eidolon_level"),
  accountRating: __t.option(__t.u32()).name("account_rating"),
});
