// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  TeamSide,
} from "./types";


export default __t.row({
  matchResultId: __t.u32().name("match_result_id"),
  userId: __t.u32().name("user_id"),
  get teamSide() {
    return TeamSide.name("team_side");
  },
  isCaptain: __t.bool().name("is_captain"),
  anonymousLabel: __t.option(__t.string()).name("anonymous_label"),
});
